### ISSUE TITLE
It doesn't seem like it will ever load. 

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#10]
I've been at the "Hi there! Some big changes are about to occur! Please wait.. This might take a while.
Note: This popup will close itself when everything is ready." for 1 hour, 25 minutes at the time of this posting, then I exited out. 

Is this expected behavior or is there a problem on my end, yours, or both?

Windows 7, 64bit
Trying out 32bit version of Happypanda v0.17 Alpha

It may well be a problem on my end, so perhaps wait for others to comment. Hopefully, maybe in the thread. I don't know. 

Also, the version v0.16 alpha was contained inside the v0.17 alpha for some reason.

Here's the entirety of the log:
21-07 13:01 INFO   version.constants Happypanda Version 0.17
21-07 13:01 INFO   version.constants OS: Windows 7

21-07 13:01 INFO   version.gui.app Invoking first time level 2
21-07 13:01 INFO   version.constants Select defaultstyle: OK
21-07 13:01 INFO   requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): raw.githubusercontent.com

**Comment by twiddli** [comment]
I'm trying to get a hotfix out as soon as possible. The issue should be resolved once you restart the application (If not, then try restarting again).
Basically what's happening is that 'first time level 2' is not being invoked properly.

**Comment by twiddli** [comment]
I forgot to mention that it shouldn't take more than a few minutes (200 galleries takes approx 1 min on my laptop).

**Comment by twiddli** [comment]
should now be fixed in v0.18
