### ISSUE TITLE
default language of added galleries changed

### ISSUE THREAD

**Issue by fr89196** [Pewpews/happypanda#103]
whenever i change the default language in my settings it also change the language of my galleries in HP. 
    1. set japanese as default language
    2. add a new gallery ->without editing<- (i don't know why but the language is in "other")
    3. close HP and reopen HP, newly added gallery is in japanese
    4. now set english as default language and close HP and reopen HP
    5. gallery is in english

this problem doesn't occur if gallery already being edited (like "get metadata").

**Comment by twiddli** [comment]
Hi, many thanks for the steps. I successfully reproduced the bug.
Will make sure to fix in the next version.
