### ISSUE TITLE
Failure to detect source deletion + Crash on gallery deletion

### ISSUE THREAD

**Issue by rignel** [Pewpews/happypanda#104]
Hello, I have a similar problem to someone in the Gitter chat, namely, HP doesn't detect source file deletion. New gallery detection works normally. Had this problem in both 0.26 and 0.27.

A new issue for me in 0.27 is crash on gallery deletion. Remove gallery/Remove and delete files both cause this.

[happypanda_debug.zip](https://github.com/Pewpews/happypanda/files/96553/happypanda_debug.zip)

**Comment by twiddli** [comment]
Hi, thanks for the log.
Didn't know it was in 0.26 too. I'll try to fix it in the next version.

As for the new bug in 0.27, I'm trying to think up a better way to handle removing galleries. The bug will hopefully fix itself when I've reworked that part.

**Comment by rignel** [comment]
Adding to the previous, it seems that 0.27 does recognise missing sources as it labels them with "gallery source is missing" in grid view. HP doesn't notify about deletions in any way though, not during launch nor in realtime.
