### ISSUE TITLE
Some covers do not display in grid view

### ISSUE THREAD

**Issue by virulence** [Pewpews/happypanda#106]
As the title says: some covers show blank both when detecting the new gallery and in the grid view. Trying to select a cover doesn't change it.

I noticed that if I extract the .zip folder into its own folder and convert one of the images from .jpg to .png, I can select it as a cover and it will display properly in grid view. Not sure why this only affects some archives of .jpgs. Size and colour don't seem to have an effect.

I recall a conversation on the github chat a few months ago about it but nothing much came of it. Problem has persisted since 0.25.

**Comment by twiddli** [comment]
This is pretty late but can you help me debug this issue?
I can't seem to reproduce this on my end.

I'll make a debug build that you need to run.

**Comment by virulence** [comment]
Sure, go ahead.

**Comment by twiddli** [comment]
Incidentally, is your OS 64bit?

**Comment by virulence** [comment]
Yep. Windows 7 Home Premium SP1, 64-bit.

**Comment by twiddli** [comment]
Please download [this](https://github.com/Pewpews/happypanda/releases/tag/v0.27.5-DEBUG) build and follow these simple steps:
- Once downloaded and extracted to somewhere not in your offical Happypanda folder, please open Happypanda (debug) in debug mode
  - To open in debug mode, append the `--debug` argument when opening Happypanda (debug) from a CMD, like this: `C:\path\to\HP\Happypanda.exe --debug`
- Next, click on the button `DEBUG BUTTON` in the toolbar
- A dialog should popup with some text. I want you to take a screenshot of this dialog and send it to me.
- Next, close the dialog by clicking _OK_ and another dialog should appear, this time with a picture.

You shouldn't be able to see this picture. If you're able to then please follow these additional steps:
- Find one of those JPG images you say won't work and copy it over to the Happypanda (debug) folder
- Rename it to `horopic.jpg`, and then repeat the steps above and see if you can see the picture.
- Post results

**Comment by virulence** [comment]
[Here's the screen capture of the dialogue.](http://puu.sh/n85uw/2e700b97e8.png) The image displayed correctly in a window after closing the dialogue.

Checked the official Happypanda for blank covers and selected one at random. Found and extracted the .zip and copied the first image in the archive to the debug Happypanda folder and renamed it. Ran the debug Happypanda again and followed the same steps. Identical dialogue. [Image did not display correctly.](http://puu.sh/n867H/699087080d.png)

Hope this helps!

**Comment by twiddli** [comment]
Can you send me the faulty image?

**Comment by virulence** [comment]
[Sure.](http://puu.sh/n8kFt/d77c7d6976.jpg)

Edit: It just occured to me that puush alters the image upon upload, so here's an [imgur link](http://i.imgur.com/bBYWAw6.jpg)

Edit2: On a hunch I downloaded the imgur image and tried the debug version again and it displays correctly. Here's a [dropbox link](https://www.dropbox.com/s/qmeqv825blimjqa/001.jpg?dl=0) instead. Maybe eze does something to the files when it downloads them; I'm not sure.

**Comment by twiddli** [comment]
Thanks for your cooperation.
The issue should now be fixed in the next version.

**Comment by virulence** [comment]
Good to hear. Looking forward to it.
