### ISSUE TITLE
"It was too big!" - error

### ISSUE THREAD

**Issue by JacobDNN** [Pewpews/happypanda#108]
After 0.27 update when i try to click on any manga, this error shows up. Thumbnails regeneration doesn't fix the problem. 

[happypanda.txt](https://github.com/Pewpews/happypanda/files/101929/happypanda.txt)

![14535599416750](https://cloud.githubusercontent.com/assets/16853960/12531136/61f9c14c-c215-11e5-89e9-d1e4e8de8a86.jpg)

[happypanda_debug.zip](https://github.com/Pewpews/happypanda/files/101930/happypanda_debug.zip)

**Comment by twiddli** [comment]
Hi, thanks for the logs.
The issue looks easy to fix.

Which version did you update from?

**Comment by JacobDNN** [comment]
I was using version 0.25.

**Comment by twiddli** [comment]
How did you update? 

To update properly while retaining your database, you just overwrite the old version. Your log tells me you moved the database to the new new version.

If I'm right, and you still have your old installation, please move it back and overwrite it with the new version.

**Comment by JacobDNN** [comment]
> just overwrite the old version

That's the first thing i tried. But i got new, clean db. My old db doesn't automaticly rebuilded as it says in the update description. There was no mesage or anything, just new db. Then i tried to rename my old db from "sadpanda.db" to "happypanda.db". After that there was a message that my db is old and need to update. I clicked "yes" and now im here. There is posibility that i lost some logs, sorry about that.

I will try go back on 0.25 version and make a new logs in few hours.

**Comment by JacobDNN** [comment]
OK, now i made a proper logs, i believe.

First of all, i go back to 0.25 version. Looks like everything works good.
[1. v25 (everything good).zip](https://github.com/Pewpews/happypanda/files/102320/1.v25.everything.good.zip)
Next i overwrite it with 0.27 version and start the programm. As before, i got new, clean db without any notification.
[2. v27 (after overwrite).zip](https://github.com/Pewpews/happypanda/files/102321/2.v27.after.overwrite.zip)
Now i rename my old db from "sadpanda.db" to "happypanda.db". A notification apears about updating db, i clicked "yes".
[3. v27 (after old DB renaming).zip](https://github.com/Pewpews/happypanda/files/102322/3.v27.after.old.DB.renaming.zip)
After updating db i restarted the programm and got the same "It was too big!" - error when clicking on any manga.
[4. v27 (after restart).zip](https://github.com/Pewpews/happypanda/files/102323/4.v27.after.restart.zip)

**Comment by twiddli** [comment]
Thanks for the detailed response.
Alright, here's what you need to do:
- Rename it back to `sadpanda.db`, download v0.26 and overwrite
- Make sure you have a file named `settings.ini` in the folder (run Happypanda v0.26 and it'll generate it for you)
- In `settings.ini`, make sure there is a section named `[Application]` and somewhere under that section an entry like this: `first time level = 4` (the number 4 is important)
  - So it should look like this: 
  
  ```
  [Application]
  first time level = 4
  ```
- Next you open Happypanda v0.26 and it'll prompt the gallery update
- Now you overwrite with v0.27 and it'll prompt the update.

**Comment by JacobDNN** [comment]
> first time level = 4

Well, i gues thats was the problem. My settings file doesn't have that line. After i added it HappyPanda successfully updated to 0.26 and then to 0.27. The error is gone and looks like everything working fine. Thank you very much.
