### ISSUE TITLE
Quibbles

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#11]
While I await v0.18, here are some quibbles. 
Either the not loading fixed itself or you did something.
The stuff in the red boxes are what's wrong.
I don't know if it's something on my end, but it's cut off on the side. Always has been.
There are some other things to say, but seems they are being fixed in 0.18. 
I'll do a more thorough check after 0.18 is out. 

![quibbles 0](https://cloud.githubusercontent.com/assets/12780404/8817612/fc7b2bbe-2ffa-11e5-9564-c34c1a51ec17.jpg)
its 
directory

![quibbles 1](https://cloud.githubusercontent.com/assets/12780404/8817624/211b99fe-2ffb-11e5-8c58-5e24d7ffa0ca.jpg)
Missing spaces

![quibbles 2](https://cloud.githubusercontent.com/assets/12780404/8817643/5d716d5c-2ffb-11e5-8f79-b73e115a0245.jpg)
missing a space
those that do not already exist
when there is more than one gallery found when searching 

![quibbles 3](https://cloud.githubusercontent.com/assets/12780404/8817676/ff70000a-2ffb-11e5-869e-aee407069606.jpg)
Is your preferred

**Comment by twiddli** [comment]
I really appreciate this.
Fixed in v0.18
