### ISSUE TITLE
Closing "Metadata fetched" popup causes happypanda to crash

### ISSUE THREAD

**Issue by nonamethanks** [Pewpews/happypanda#110]
Arch Linux & Openbox & Tint2 as a taskbar.
When fetching metadata for a gallery, a popup saying "Successfully fetched metadata" will show up on the taskbar. Hitting the [X] button on the popup will cause happypanda to crash abruptly and return a core dump.

I couldn't get anything interesting from the debug log, since nothing different shows up if I instead let the popup disappear on its own (the difference is that the program doesn't crash in this case) so I tried to debug with gdb and this is the result:
http://pastebin.com/nBfDVjJ1

**Comment by twiddli** [comment]
Hi, I'll try and see if I can reproduce.

**Comment by twiddli** [comment]
I successfully reproduced this issue. I'll try and think up a fix.
