### ISSUE TITLE
"exclude in auto metadata fetch" option for gallery selection

### ISSUE THREAD

**Issue by shadeus** [Pewpews/happypanda#111]
The "exclude in auto metadata fetch" option is a nice feature, but I have 200+ galleries I wish to exclude So a way to exclude a selection of galleries would be great

Also, is there a way to list galleries that have not had their metadata updated through the HP automation?

**Comment by twiddli** [comment]
I actually forgot to answer your question. 

> Also, is there a way to list galleries that have not had their metadata updated through the HP automation?

Depending on what you mean then the search term `tag:none` may be what you want. Please take a read on [how to search for galleries](https://github.com/Pewpews/happypanda/wiki/Gallery-Searching) to find out more.

**Comment by shadeus** [comment]
> Depending on what you mean then the search term tag:none may be what you want. Please take a read on how to search for galleries to find out more.

Thanks, can't believe I missed that.
