### ISSUE TITLE
Stops getting metadata after a while

### ISSUE THREAD

**Issue by 404Fox** [Pewpews/happypanda#116]
After activating the metadata getter for all my galleries, it eventually stops working after a while, and the screen is blurred.

**Comment by twiddli** [comment]
Hi, please provide me your log or else I won't know what's wrong.

**Comment by 404Fox** [comment]
[happypanda log.zip](https://github.com/Pewpews/happypanda/files/124018/happypanda.log.zip)
After closing it out, the metadata loading thing on the top right remains and it has to be closed by task manager.

**Comment by twiddli** [comment]
Is the issue apparent? 
Can you reproduce it? If yes, how?
Also, can you please follow [this](https://github.com/Pewpews/happypanda/wiki#bug-reporting) guide on how to report. Thanks.

**Comment by 404Fox** [comment]
Ah, I'll use the get metadata for all galleries button, then let it run.
When I come back to it, it looks like this
![untitled](https://cloud.githubusercontent.com/assets/16171681/13129227/1d6065a0-d5a1-11e5-9d21-2e8242e9e655.png)
(without the black paint)
and if I close it out, the metadata loading box does not go away, and has to be killed with task manager. Starting happypanda again without killing it will create another instance, and the bug can be reproduced for multiple metadata boxes.

**Comment by twiddli** [comment]
Thanks for the details.. Can you please produce a debug log as shown in the guide I linked in my previous post? Thank you.

**Comment by 404Fox** [comment]
[happypanda_debug.zip](https://github.com/Pewpews/happypanda/files/137315/happypanda_debug.zip)

**Comment by twiddli** [comment]
Hi, please tell me if this still happens in v0.29.
