### ISSUE TITLE
Can't get metadata with the 0.27

### ISSUE THREAD

**Issue by Santosus** [Pewpews/happypanda#117]
I was fine with the 0.26 but with the recent change to login/password I remembered that I forgot my password at exhentai and created a new one however this new version can't get to login.
the error seems to be this:

05-02 01:50 INFO   fetch  Initiating auto metadata fetcher
05-02 01:50 INFO   fetch  Auto metadata fetcher is now running
05-02 01:50 INFO   fetch  using ehen
05-02 01:50 INFO   fetch  Checking gallery url
05-02 01:50 INFO   fetch  Generating gallery hash: b'(C89)  Healing Decision (THE IDOLM@STER CINDERELLA GIRLS)  {YQII}'
05-02 01:50 INFO   pewnet Initiating hash search on ehentai
05-02 01:50 INFO   requests.packages.urllib3.connectionpool Starting new HTTP connection (1): exhentai.org
05-02 01:51 INFO   requests.packages.urllib3.connectionpool Starting new HTTP connection (1): forums.e-hentai.org
05-02 01:51 ERROR  pewnet Provided exhentai credentials are incorrect!
05-02 01:51 INFO   fetch  Auto metadata fetcher is done
05-02 01:51 CRITICAL app      File "C:\Users\Autriche\Documents\GitHub\happypanda\version\app.py", line 359, in done

05-02 01:51 CRITICAL app    <class 'RuntimeError'>: wrapped C/C++ object of type Fetch has been deleted

**Comment by twiddli** [comment]
Hi, there's a known bug where you won't be able to login because you weren't given access to EX through Happypanda. The issue has been fixed, and I will implement methods to access EX provided you have your ipb id and pass hash. Expect this in the next version.

**Comment by twiddli** [comment]
Just a note:
You can still fetch metadata from g.e-hentai by choosing g.e-hentai as your default URL in settings.

**Comment by Santosus** [comment]
Hi, thanks for the answer, and is just as you said and the problem is only with EX, g-e goes normally 
and I still have ipb id and pass hash.
