### ISSUE TITLE
Can't get metadata for some galleries

### ISSUE THREAD

**Issue by JacobDNN** [Pewpews/happypanda#119]
Hi. I have some galleries that originally aren't from exhentai, but have the same or similar filenames. Happypanda successfully imports them, recognizes titles and authors, but can't auto get metadata.

[Screenshot1](https://cloud.githubusercontent.com/assets/16853960/12919042/212b4a26-cf64-11e5-88f8-53b36845c496.png)
[Screenshot2](https://cloud.githubusercontent.com/assets/16853960/12919048/238b66c0-cf64-11e5-8f88-74fb68b79bc5.png)

[debug.zip](https://github.com/Pewpews/happypanda/files/123177/debug.zip)

**Comment by twiddli** [comment]
Hi, I think I know why it fails.
Could you maybe send me the archive in question so I can do some tests?
Thanks.

**Comment by JacobDNN** [comment]
Sure. 
https://mega.nz/#!YlZ0ibZa!gWAd6a_RSerC1giPqNT7tzGenIo0y0CyZtm6sE-6v9c
