### ISSUE TITLE
Populating database gets stuck at 43%

### ISSUE THREAD

**Issue by edgar1016** [Pewpews/happypanda#12]
Hi Im the anon from /h/ having issues running to program. I have the same issue with 0.19 I have HP installed on my desktop and all the files i'm adding are on a different HDD which on my PC is D:/. Here is the log file hope you can help thanks.
http://pastebin.com/J7UBxfYJ

**Comment by twiddli** [comment]
Hi, can you provide me some more info? How does your folder look inside?
The log tells me that there are 414 items but only 376 gets imported, does this mean that there are files of different formats (not zip/cbz or a directory)?
In any case, can you try running the program with the --debug argument and provide me the file named 'happypanda_debug.log' that get's created?
To run the program with the --debug arg, follow these steps:
1. Open folder explorer and navigate to where you downloaded Happypanda
2. Click on the URL-bar inside the folder explorer once (this should select everything), type 'cmd' and press enter
3. Write 'Happypanda.exe --debug' (without the single quotes) in the console and press enter
4. Now try importing again and let it get stuck.
5. Go back to folder explorer and a new file called 'happypanda_debug.log' should appear.

Cheers~

**Comment by edgar1016** [comment]
Yes in the folder there are some rars I believe. Here's the debug log.
https://drive.google.com/file/d/0ByJzXArmDRY2SEtwdmNUaGszM2s/view?usp=sharing

**Comment by twiddli** [comment]
Try moving this file outside the folder and try populating again:
[Kawaisounako (Yuyu, Ichino)] Deep Snow Soushuuhen 1-6 (Mahouka Koukou no Rettousei) [English] {The Lusty Lady Project + EHCove + hardicondor + inhibitionkiller007}.zip

Also, i recommend joining the gitter chat for faster replies:
https://gitter.im/Pewpews/happypanda
It only requires your github account.

**Comment by twiddli** [comment]
Fixed
