### ISSUE TITLE
Can't Open ZIPs/RARs through 0.27

### ISSUE THREAD

**Issue by FireSempai** [Pewpews/happypanda#120]
Read the title, 
all of the h-mangas/cg sets that I have in a zip/rar won't open through Happypanda.

**Comment by twiddli** [comment]
Hi, please open settings in Happypanda, go to `About->Bug Reporting` and read the guide.
I can't really help if I don't get more information since none of this happens to me or others.

**Comment by FireSempai** [comment]
Ok, I actually can't manage to send a copy of my log.
What should I do?
