### ISSUE TITLE
change how the dup manager is displayed

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#123]
i think the dupe manager right now needs to be changed in one of two ways.
either 1 let it have it own side widget that will not cover up things in the thumbnail view (move everything to the side like the widget you have now).

or 2, let it open its own view tab. a tab like the library but only displays the dupes it finds.

both of these will make dupe managing alot easier and faster to do in general.

i do think the tap is the best of the two tho as no other issues/volumes will be on display at all when you have it set up like that.

ofc when you delete one part of the dupe (should check if there is any remaining incase if there is more than two dupes) then the other part that you DIDNT delete should be removed from view aswell so its out of the way.

**Comment by twiddli** [comment]
Hi, I'm definitely going to improve the duplicate checker as per #51 
Both of your suggestions are good and I will keep them in mind when improving it.
