### ISSUE TITLE
Gallery info window doesn't stay open

### ISSUE THREAD

**Issue by nonamethanks** [Pewpews/happypanda#125]
Arch linux.
Every version since this commit https://github.com/Pewpews/happypanda/commit/c3af1a9f9c9bf8f9cb88e2cf35ecfea204b5c626 has this bug for me. 

Basically, this happens: https://a.pomf.cat/vzlmqf.webm (I'm using the latest release, v0.28, for this example).
If I click on a gallery, the info popup only stays open for an instant and then closes itself immediately. 
http://pastebin.com/NEicNGWL this is my debug log.

**Comment by nonamethanks** [comment]
I should also note that I tried the version right before that commit and it works without problem, so it's definitely something in that commit that is causing this problem.

**Comment by twiddli** [comment]
Hi, can you please try the latest commit in alpha branch to check and see if the issue has been fixed? Thank you.

**Comment by nonamethanks** [comment]
Yep, it works now!
