### ISSUE TITLE
Thumbnail issue in 0.28

### ISSUE THREAD

**Issue by rignel** [Pewpews/happypanda#127]
Earlier I had problems with not being able to delete galleries without crashing HP, but noticed that on a fresh database there were no problems. I started to build my database back up from scratch, but now adding some galleries give me the "It was too big!" error.
[happypanda_debug.zip](https://github.com/Pewpews/happypanda/files/144060/happypanda_debug.zip)

**Comment by twiddli** [comment]
Hi, can you send me the first image in `E:/[Fukuyama Naoto] Attameaikko   Let's Warm Up Together (Tsuyumamire) [English] [PSYN].zip` for debugging purposes?

**Comment by rignel** [comment]
Here's two from different galleries that can't be added. Works just fine in 0.27.

[Attameaikko 01.zip](https://github.com/Pewpews/happypanda/files/145170/Attameaikko.01.zip)
[Summer Embrace 01.zip](https://github.com/Pewpews/happypanda/files/145171/Summer.Embrace.01.zip)
