### ISSUE TITLE
Problem with adding specific gallery

### ISSUE THREAD

**Issue by anon113** [Pewpews/happypanda#128]
I can't add one specific gallery to the happypanda.
Also, it probably has some unwanted behavior when fetching metadata process is failed.

Video:
https://dl.dropboxusercontent.com/s/rt0jr2jyk9bfeq0/2016-02-24_17-23-56.mp4

Log:
https://dl.dropbox.com/s/pfbo4k2ro7i7l2s/happypanda_debug.log

Problem gallery:
https://dl.dropbox.com/s/x8vnrglymochovz/%5BCampanula%20%28Akihazama%29%5D%20Absolute%20Semen-Idol%20Declaration%20%28English%29.zip

**Comment by twiddli** [comment]
Hi, this might be bug in the module [zipfile](https://docs.python.org/3/library/zipfile.html) that I'm using to manage zip files. The issue occurs when trying to list all directories in the file. No directories are returned, and as such the file is treated as if it's empty.
You can fix this yourself by moving all the images in the zip file one directory up.

I will report this and we'll see where it'll end up!
