### ISSUE TITLE
Main view is not automatically updated when galleries are added automatically

### ISSUE THREAD

**Issue by nonamethanks** [Pewpews/happypanda#138]
This is a minor thing, but whenever a new gallery is added after detection by the folder monitoring function, the software does not automatically update the list as it should, so it's necessary to hit the Enter key inside the search bar to manually update it.

Also in the shortcut sheet there doesn't seem to be a key set for refreshing the main page, so probably setting F5 or something like R/Alt+R to it would be best.

Edit: this is also a problem for when you search for a specific tag and then edit out one of the results from it. The gallery in question will still remain part of the results until you refresh (still by searching for it again).

**Comment by twiddli** [comment]
Fixed in v0.29.

> this is also a problem for when you search for a specific tag and then edit out one of the results from it. The gallery in question will still remain part of the results until you refresh (still by searching for it again).

This is intentional.
