### ISSUE TITLE
Most galleries for which metadata is fetched have language set to chinese instead of japanese

### ISSUE THREAD

**Issue by nonamethanks** [Pewpews/happypanda#140]
Title says it all. Whenever a gallery whose language is not set on e-hentai (which is, the japanese galleries, which have no language tags unlike translated works) is fetched, the program sets the language to chinese instead of japanese. 

This is extremely annoying because it happens with every single gallery with no "language" namespace, so I have to manually set the language back to japanese for dozens of galleries one by one whenever I add them in bulk.

I already have "Japanese" set  under Gallery > Default Language.

[happypanda_debug.log](https://my.mixtape.moe/nmwggf.log)

**Comment by nonamethanks** [comment]
After a couple of tests it seems some other galleries are instead correctly fetched as japanese, like http://exhentai.org/g/898072/d9b4f73397/ or http://exhentai.org/g/898072/d9b4f73397/, however the vast majority of them is affected by this problem.

**Comment by twiddli** [comment]
Hi, can you provide a link to a gallery that is affected?

**Comment by nonamethanks** [comment]
http://exhentai.org/g/906315/d4e9595d21/
http://exhentai.org/g/910319/2d4e654b50/
http://exhentai.org/g/839094/4ea8f5ba83/

Example of what happens after fetching metadata for one of these: http://i.imgur.com/gPhUqLM.png
http://i.imgur.com/r23RoWb.png (you'll notice that here instead of showing the language on the top right after the category it'll just have an empty line, but it still shows "chinese" when you open the edit metadata window)

**Comment by twiddli** [comment]
Thanks!
