### ISSUE TITLE
I can't get metadata from exhentai

### ISSUE THREAD

**Issue by smaug3001** [Pewpews/happypanda#152]
I am having trouble setting the program to look to exhentai for tags. It just stubbornly goes to g.e-hentai first:

default EH value is exhentai
Login pass doesn't work (in fact it never worked for me in any version).
When you set cookie values directly, it doesn't save them.
When you add those at settings.ini it still doesn't work.
If you directy add exhentai URL of a gallery, it claims to successfully get the metadata. But according to logs, the tags still come from g.e-hentai.

As far as tags concerned, it's not really a big deal. But i don't want to fix every file's source manually.

**Comment by twiddli** [comment]
Hi, setting cookie values in `settings.ini` is _deprecated_. Cookies are saved elsewhere now.

By login-pass, you mean trying to sign in at `Web -> Logins` doesn't work?
If so, have you tried filling in your ExH details at `Advanced -> Misc`?

If yes and yes, could you post a log so I could take a look at it?

**Comment by smaug3001** [comment]
Yes and Yes. Also yesterday i noticed that you uploaded 0.30, and tried a new installation, logfile is
from that one. I retried the stuff above again right before copying the logs, so you can look directly at the bottom.

[happypanda.txt](https://github.com/Pewpews/happypanda/files/280266/happypanda.txt)

**Comment by twiddli** [comment]
I've looked through your log and it indeed fails to sign-in.
By any chance, are you using a proxy? In your browser, that is.

I haven't implemented any proxy handling yet.

**Comment by twiddli** [comment]
Also, when you put in your ipb values, close the settings window, open it up again, and then go to `Web->Logins`, does it say `Logged in!` in green?

**Comment by smaug3001** [comment]
Nope, it said not logged in.

But after you asked about the proxy, i looked at the logs. You're trying to login through forums.e-hentai, and my browser wasn't opening it itself, despite it can open g.e or ex. I retried web-login again when i was on a vpn, and it worked this time.

**Comment by twiddli** [comment]
I'm glad the issue has been resolved. I'll probably implement some proxy handling some time.
