### ISSUE TITLE
Gallery Downloader Python AttributeError

### ISSUE THREAD

**Issue by robertdhernandez** [Pewpews/happypanda#155]
When I try to use the gallery downloader, it keeps telling me a python exception occurred. The weird thing is that directory doesn't even exist.

> 04-06 16:48 CRITICAL app      File "C:\Users\Autriche\Documents\GitHub\happypanda\version\io_misc.py", line 297, in add_download_entry
>   File "C:\Users\Autriche\Documents\GitHub\happypanda\version\pewnet.py", line 479, in from_gallery_url
> 
> 04-06 16:48 CRITICAL app    <class 'AttributeError'>: 'NoneType' object has no attribute 'get'

[Full log](http://pastebin.com/3XQ566FT)

**Comment by twiddli** [comment]
All gallery downloader issues should be fixed in v1.0
