### ISSUE TITLE
Gallery Downloader "Gallery could not be added!"

### ISSUE THREAD

**Issue by arisune** [Pewpews/happypanda#156]
Hello Pewpews,

I've had a problem with the downloader for a while now when I'm batch downloading from exhentai.
There seem to be always a few galleries which can't be added, I have to fetch the metadata after instead of having it automatically added during the download.

Here is a screenshot of the downloader:
http://puu.sh/pilM7/ea29724dc7.png

And here the log of the test batch:
http://puu.sh/pimqz/abf439bd3b.txt

This is the path:
H:\同人誌\日本語

Really appreciate the work you put into this program and that you coded it in the first place.
Thank you!

**Comment by twiddli** [comment]
Will be fixed in version 0.31
