### ISSUE TITLE
Adding network directories

### ISSUE THREAD

**Issue by Kradziej** [Pewpews/happypanda#157]
Is there any way to add network shared folder to library? I tried to add one first by simply using add galleries button and pasting URL into file browser but i got this

14-06 12:58 INFO   app    Populating DB from directory/archive
14-06 12:58 INFO   fetch  Gallery folder is not empty
14-06 12:58 INFO   fetch  Received 1 paths
14-06 12:58 INFO   fetch  Treating each subfolder as chapter
14-06 12:58 INFO   fetch  Creating gallery: b'!@NEW'
14-06 12:58 INFO   fetch  Gallery source is a directory
14-06 12:58 INFO   fetch  Gallery has 1371 chapters
14-06 12:58 WARNING fetch  Skipped b'//XXX/Anime/H-manga/!@NEW' in local search
14-06 12:58 INFO   fetch  Local search: OK
14-06 12:58 INFO   fetch  Created 0 items
14-06 12:58 ERROR  app    Populating DB from gallery folder: Nothing was added!

with populate from directory/archive button it correctly finds galleries but with blank URL and after adding ~170 i tried to move it from inbox to library and got this

14-06 13:00 CRITICAL app      File "C:\Users\Autriche\Documents\GitHub\happypanda\version\misc.py", line 1192, in send_to_lib
  File "C:\Users\Autriche\Documents\GitHub\happypanda\version\gallery.py", line 1612, in add_gallery
14-06 13:00 CRITICAL app    <class 'NameError'>: name 'Executors' is not defined

I guess it's just a feature not yet added to program but maybe I'm doing something wrong

**Comment by Kradziej** [comment]
I kinda figured it out, with "subdirs should be treated as standalone..." setting checked you can add galleries from network folder without problems. 
Unfortunately scanning speed as for my needs is waaaaaaay too low even if i connect computers directly with lan cable. Network folder with ~1400 folders and archives was fetched around 3h and it's ok, but if I want to rescan for new files (and I'm adding things to this folder regularly so it's must) it's taking around half of it to just add few new files.
But that's whole different issue I think

**Comment by twiddli** [comment]
Hi, this should be fixed in v1.0
