### ISSUE TITLE
Metadata not working?

### ISSUE THREAD

**Issue by Indy27** [Pewpews/happypanda#161]
I remember a time I tried 0.27 and 0.29 (my first one, and the one I still use today is 0.26) and after configuring everything, tried to fetch the metadata, only for the program to crash every time so I went back to 0.26.

Now I decided to try 0.30 for the first time and see if the crashing problem has been fixed, but instead have another problem; the screen goes blurred and metadata hasn't fetched the first gallery in hours!

What is going on? I really don't want to go back to 0.26 which seems to be the only stable version out there.

**Comment by Indy27** [comment]
Okay, I actually posted wrong version: I'm using 0.25.

**Comment by twiddli** [comment]
Hi, it does seem like the auto metadata fetcher isn't functional at the moment. I will work on a fix in a new version of HP.

**Comment by dillingercontrol** [comment]
Are you using a NAS or network drive? I have had a similar issue when I added a network location to monitor galleries from and I got the same blurry screen on startup. The solution is to delete your settings file and use a local drive to monitor imports from. You can use a network drive as your library location as long as it is not monitored by HP.

**Comment by twiddli** [comment]
All metadata issues should be fixed in v1.0
