### ISSUE TITLE
Start over

### ISSUE THREAD

**Issue by twiddli** [Pewpews/happypanda#162]
Hello guys who still follow this project.

As you've noticed, I haven't been active at all these past months.

There are several reasons for that, one being school, another is lack of interest (I don't use HP that much anymore), and maybe the biggest of them all is Qt (the framework used for the GUI) and Python.

When I started working on HP, I was still new to Python and most of all Qt. This led to me making poor deci- ah whatever!

**BOTTOMLINE**
- Codebase is horrifying, not enjoying working with it anymore
- Qt(PyQt) is annoying to work with, I went in without knowing anything, this time it should be alright
- Maybe I should make this in C++

_I want to start over_

**Comment by Zuescho** [comment]
Great to hear from you again, yeah sad to hear you dont use it as much anymore. I'm myself used it more like an archive database than a reader but i always enjoyed it.

Do you now have more time besides school so you can get more dedicated to the start over?

**Comment by twiddli** [comment]
Yes, I'm all for starting over. Truth be told, I did actually work on HP since the last update where I tried to redo the internal DB structure and change the way galleries are handled. This, of course, was a nightmare and made me question why I was torturing myself like that, at which point I just snapped and said fuck it.

![python_2016-10-02_23-55-19](https://cloud.githubusercontent.com/assets/11841002/19024025/bc26e1ec-88fb-11e6-8917-e1e5310fa5a8.png)

I do actually want to create an application to manage my stuff, but if I'm going to do this, I'd need to start over, which is totally okay with me. I mean.. there is no rush.. lol. 

Uhh about time, yes I have that. I tend to put all my time into a project If i get too invested. If it goes well, you'll see faster releases, if not, then... probably not as fast releases. The good thing is that I already got the internal DB structure down.

**Comment by Zuescho** [comment]
Looks great, i wish you the best luck with the project, i will keep a close eye.
To my knowledge you are the last one to do this, so heads up

**Comment by twiddli** [comment]
just a correction, that screenshot is a shot of HP _before_ i quit, not the new one.

**Comment by DawgNewb** [comment]
I was about to try ya programez today, but suddenly #162.
Maybe I'll try again next release. No need to rush and take care :)

**Comment by Indy27** [comment]
Maybe you should, you know, _get help from people who're interested in working/coding/whatever this program_. Faster releases and less bugs, I think.

**Comment by ghost** [comment]
@indy27 that is  bit obvious though honestly. 

glad you're still around Pewpews. I'm fine with you starting over, hope it goes well!

**Comment by twiddli** [comment]
@Indy27 Oh, thanks for the suggestion. Maybe I should host the project on Github, which makes it _very easy_ for, _you know_, other people to chime in as well.

**Comment by twiddli** [comment]
@Indy27 though, if you're able to and want to help, that would be great.

**Comment by Indy27** [comment]
Why not use ajax/js? Are they more difficult than coding in python?

**Comment by twiddli** [comment]
You mean using something like http://electron.atom.io/? Doable, but honestly no clue if it'll fix the issues I had with PyQt. Also, Python isn't difficult for me and has never been, just, stupid GUI library. We could totally try out using Electron if you're inclined on helping.

**Comment by Indy27** [comment]
Maybe someone with js/css experience can help you (unfortunately I'm not one of them, and I tried python but it was just a pain in the ass; I only know little about html) but electron may look like something that could easily work with their auto-update and other stuff.

**Comment by pandabuilder** [comment]
Maybe separate the back end from the front end? That would open the possibility to use it with multiple clients, and a different language for the frontend.

**Comment by twiddli** [comment]
Yes, that's exactly what I'll be trying to do this time around.

**Comment by emmauss** [comment]
is it possible to make an android port?
and also , isnt it difficult to make a gui app with c++, even with QT as a frontend?

**Comment by twiddli** [comment]
Hello, yes it will be possible to make an android client with the new HP. In the future, maybe, if someone hasn't already, I might make something for android.
Well I like C++ more than Python so that's why.

**Comment by emmauss** [comment]
is the new HP any different from HPX, because you seem to reqularly update that, although you halted master when you opened this issue.

**Comment by twiddli** [comment]
HPX is the new HP :) I will eventually merge it over to the master branch when I've got a somewhat working version.

**Comment by dillingercontrol** [comment]
The biggest questions I have are: is HPX usable in a "production environment" and are the databases backward and forwards compatible?

**Comment by twiddli** [comment]
HPX database will not be backwards compatible with old HP database. On HPX "server" launch, data will automatically be pulled out from the old database and put in the new one. If you have a better idea or suggestion please tell me.
The workflow for HPX is _much_ better than it ever was for old HP. Continuous integration services/practices will be used to ensure a proper application before publishing. Though, as of now, HPX is still being worked on so nothing usable yet.

**Comment by dillingercontrol** [comment]
Importing HP's database to HPX is a good idea since HP will be depreciated in favor of HPX and it's updated database structure.

HP is robust and I haven't had any real trouble using it. I might try to do a few QoL fixes for HP while you work on HPX since it appears to be your primary focus.

**Comment by rachmadaniHaryono** [comment]
@Pewpews is new HPX will use sqlite3? becaues i have seen how complicated the database module. have you consider using http://docs.peewee-orm.com/en/latest/index.html? it is a bit simpler and similar to django model.

**Comment by twiddli** [comment]
@rachmadaniHaryono I did take a look at peewee before settling for [SQLalchemy](http://www.sqlalchemy.org/). Peewee _does_ seem much simpler though. I will reevaluate and see if it's up for the job. Thanks.

**Comment by rachmadaniHaryono** [comment]
@Pewpews i don't know if i am the correct person, but can i suggest these things for the new happypanda

- use code linter e.g flake8
- any reason for using xml(?)? why not using other structure such as json etc?
- is it possible for one class one file? i understand some class and the function in some file may be related, but there are maybe  some class which can be put on a single file.
- is [happy_socketio](https://github.com/Pewpews/happypanda/tree/happypandaX/happypanda/clients/web/happy_socketio) is [this](https://github.com/Pewpews/Flask-SocketIO)? why not pip install module?
- maybe starting sphinx doc? there are some function and class which already have good docs.

**Comment by twiddli** [comment]
@rachmadaniHaryono

* I did install flake8 but forgot all about it :( I will try and see if I can configure it to autorun on save. 
* I did look at most of them before choosing. Why in particular I chose XML over JSON is because it's easier to describe the data in XML. It's still not too late to switch though, do you hate XML? JSON might be better in this case because of speed. I will sleep on it. 
* I wanted to avoid a project with hundreds of files but I see that [some](https://github.com/Pewpews/happypanda/blob/happypandaX/happypanda/common/utils.py#L15) classes may have a need for a file of their own. I can start putting bigger classes in their own files if that's what you want.
* Yes happy_socketio is that fork. You mean installing and using the [original](https://github.com/miguelgrinberg/Flask-SocketIO) module? I forked that module and [added](https://github.com/Pewpews/Flask-SocketIO/commit/6e6a9fc299ecbb99f6ca134ac670aee0ffe58580) a few stuff so it was easier to incorporate it into the project.
* I have been waiting for the code to be abit more stable before using it

**Comment by rachmadaniHaryono** [comment]
>do you hate XML?

rather hate, i see python have [json module](https://docs.python.org/3/library/json.html) which made it quite easy to convert from variable/class. there is also other such as yaml which is more readable and (c)pickle which is faster.. 

[comparison json vs pickle](http://stackoverflow.com/questions/2259270/pickle-or-json)

also if you are using flask, there is jsonify method which do the same 


http://flask.pocoo.org/docs/0.11/api/#flask.json.jsonify


>I wanted to avoid a project with hundreds of files but I see that some classes may have a need for a file of their own. I can start putting bigger classes in their own files if that's what you want.

i have seen the old happypanda files which have around 2000 lines. while IDE have easier overview for those file, editing and organizing those class can be quite nightmare (just like what you said to @emmauss). 

i have played with old HP and try `one class one file` and i think i failed. even with that some sub module is needed and better naming convention is required.

see other cases where it fails

- http://stackoverflow.com/questions/29914101/python-one-single-module-file-py-for-each-class
- http://stackoverflow.com/questions/106896/how-many-python-classes-should-i-put-in-one-file

>Yes happy_socketio is that fork. You mean installing and using the original module? I forked that module and added a few stuff so it was easier to incorporate it into the project.

if you are using virtualenv (and i recommend you should) you can install github fork using pip. you can also add github fork in `requirements.txt`. see this link http://stackoverflow.com/questions/30292039/pip-install-forked-github-repo

>I did install flake8 but forgot all about it :( I will try and see if I can configure it to autorun on save.

fyi if you use git cli, you can add flake8 git hook see these links

- https://www.stavros.io/posts/more-pep8-git-hooks/
- http://flake8.pycqa.org/en/latest/user/using-hooks.html

---

other things:

- is it required to have class/function in class/function?

i work on the same project which actually do the same thing. after my googling, i found out it is actually the routine practice on qt project. but if it is on usual python class, maybe make it as outer weak internal function(function with one leading underscore)?

see this case http://stackoverflow.com/q/326910

- is it possible to differentiate where module which only contain global variable, and module which only have class/function? or is it correct to do so? 

e.g. `app_constants.py` IMO is the correct one where there is little logic involved (even thought i'm not quite sure why some variable is changed despite the module name.)

but is `settings.py` correct?

**Comment by twiddli** [comment]
>rather hate, i see python have json module which made it quite easy to convert from variable/class. there is also other such as yaml which is more readable, (c)pickle which is faster..

>comparison json vs pickle

Just for clarification, `XML` is the message format clients and the server use to talk to eachothers with over TCP/IP.
Using `cpickle` here is totally out of the question since clients might be created in a different language. 

It's possible to replace `XML` with `JSON`/`YAML` though.

>see other cases where it fails

   *  http://stackoverflow.com/questions/29914101/python-one-single-module-file-py-for-each-class
   * http://stackoverflow.com/questions/106896/how-many-python-classes-should-i-put-in-one-file

I'm confused. I thought you wanted one class one file? 

>you can install github fork using pip. you can also add github fork in requirements.txt. see this link http://stackoverflow.com/questions/30292039/pip-install-forked-github-repo

Oh I didn't know this was possible. This does certainly make it a bit easier. I will do this.

>fyi if you use git cli, you can add flake8 git hook see these links

Nice, thanks. Just what I needed. 

>is it required to have class/function in class/function?

Are you talking about distinguishing between private and public functions? Can you elaborate with an example from the project?

>is it possible to differentiate where module which only contain global variable, and module which only have class/function? or is it correct to do so?

Yes I see what you mean, but am I not already doing that in the new project? Maybe you want `exceptions_constants.py` instead of `exceptions.py`? That's no issue at all. We can change that if you want. Also, I'm pretty sure `constants.py` will be the only one with not much logic involved.

**Comment by simonrule** [comment]
could you please in the new version add feature that will allow us to fetch from other sites like nhentai

**Comment by twiddli** [comment]
@simonrule 
Hi, implementing fetching from other sources has been on my TODO list for a long time.
I will implement this for the initial release of the new happypanda.

**Comment by ghost** [comment]
Hello. Could you add support for reading metadata information from [ComicRack](comicrack.cyolito.com/), ComicBookLover and [Doujin Renamer](https://doujinrenamer.wordpress.com/) metadata formats?. Ability to write tags in above formats to the files would also be great.

**Comment by rachmadaniHaryono** [comment]
@simonrule do you want to test my nhen parser? [happypanda/dev](https://github.com/rachmadaniHaryono/happypanda/tree/dev)

**Comment by simonrule** [comment]
@rachmadaniHaryono yes that will be great
