### ISSUE TITLE
ImportError: No module named 'PyQt5' on Mac

### ISSUE THREAD

**Issue by Flappaslappa** [Pewpews/happypanda#166]
At first it was giving an Import Error of "No module named scandir"
but I was able to get rid of that by deleting scandir and reinstalling it in /usr/local/lib/python3.5/site-packages

then I get "No module named PyQt5"

I see PyQt5 in my site-packages. 

Im on MacOs Sierra 10.12.1

**Comment by twiddli** [comment]
>deleting scandir and reinstalling it in /usr/local/lib/python3.5/site-packages

Did you try reinstalling PyQt5 too?

`pip3 uninstall pyqt5`
and then
`pip3 install pyqt5`

**Comment by Flappaslappa** [comment]
so I installed PyQt5 through pip3 and that worked 👍 
So maybe remove the disclaimer in install.md saying that "PyQt5 must be installed using Homebrew and not pip" ? 

None the less, thank you for the reply and hard work on program. Look forward to using it 💯

**Comment by bkarlson** [comment]
For strayed googlers: I had to update Python from 3.4 to 3.6 to get PyQt5 and libgit2 installed via pip3.
