### ISSUE TITLE
Happypanda v0.20 wont finish rebuilding/loading :/

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#17]
i tried both 64 bit and 32 bit and its not doing anything
pic related http://i.imgur.com/NxNpAuJ.jpg

i tried running it as an admin and as windows 7 in compatibility mode but no luck there

0.19 works fine tho

**Comment by twiddli** [comment]
Can you paste the happypanda_debug.log file? Run Happypanda with the --debug argument to create it. To do that you need to open console and launch Happypanda like this: "Happypanda.exe --debug" or "main.py --debug" if you run from source. 
The file should then be created in the directory where Happypanda is resided.

How big is your collection?

Sorry for the inconvenience, I thought I had fixed this..

**Comment by ghost** [comment]
i'm testing it with 10~ chapters on the 0.20 build
how do i open the console

**Comment by twiddli** [comment]
Sorry if I wasn't clear. Open Command Prompt and cd your way into the folder where Happypanda is resided. E.g. something like: 'cd C:path/to/hp/folder'. Then start Happypanda by writing this: 'Happypanda.exe --debug' (without the quotes).
Now try importing the galleries again. 
A file named happypanda_debug.log should appear in the folder. Copy Paste the contents of the file. If it's too long then use something like Pastebin.

Thank you, and sorry for the unclear message. 

To open command prompt on windows 7:
Click on the Windows icon. 
Write 'cmd' and press enter

**Comment by ghost** [comment]
08-08 07:54 INFO   **main** Happypanda Version 0.2
08-08 07:54 INFO   **main** OS: Windows 8

08-08 07:54 DEBUG  database.db Checking DB Version
08-08 07:54 DEBUG  **main** Init DB Conn: OK
08-08 07:54 INFO   **main** DB Version: 0.21
08-08 07:54 DEBUG  database.db Start Database Thread: OK
08-08 07:54 DEBUG  database.db Checking DB Version
08-08 07:54 DEBUG  app    Create manga display: OK
08-08 07:54 DEBUG  app    Create toolbar: OK
08-08 07:54 DEBUG  app    Create statusbar: OK
08-08 07:54 DEBUG  app    Create system tray: OK
08-08 07:54 DEBUG  app    Show window: OK
08-08 07:54 DEBUG  app    Create notificationbar: OK
08-08 07:54 DEBUG  app    Window Create: OK
08-08 07:54 INFO   app    Invoking first time level 3
08-08 07:54 INFO   **main** Select defaultstyle: OK
08-08 07:54 DEBUG  **main** Create temp: OK
08-08 07:54 DEBUG  app    Checking Update
08-08 07:54 INFO   requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): raw.githubusercontent.com
08-08 07:54 DEBUG  requests.packages.urllib3.connectionpool "GET /Pewpews/happypanda/master/VS.txt HTTP/1.1" 200 24
08-08 07:54 INFO   app    Received version: 0.2
Current version: 0.2

**Comment by twiddli** [comment]
To resolve this issue open settings.ini and add this under [Application]:
first time level = 3

settings.ini can be found in the same folder as Happypanda.exe.
Sorry for the trouble.

**Comment by ghost** [comment]
nice it worked, ty

**Comment by ghost** [comment]
on version 0.20, the progress bar doesn't change if i move and drag multiple chapters at once
if i drag 2-3 chapters each time, it works fine though

**Comment by twiddli** [comment]
I'll look into it.

**Comment by twiddli** [comment]
I can't seem to replicate this issue. If this still happens in v0.21 then please inform me about it.

**Comment by ghost** [comment]
i'm trying the new build and it's still loading until i add first time level = 3 in settings.ini

also it stops at 35% while finding metadata, same for adding multiple chapters, it stops at 43/118 and then it tries to load..

**Comment by twiddli** [comment]
Could I ask you to run in debug mode (same process as before), and try replicating those issues? After that, please provide me _happypanda_debug.log_.
Thank you for your help.

**Comment by ghost** [comment]
11-08 11:33 INFO   **main** Happypanda Version 0.21
11-08 11:33 INFO   **main** OS: Windows 8

11-08 11:33 DEBUG  database.db Checking DB Version
11-08 11:33 DEBUG  **main** Init DB Conn: OK
11-08 11:33 INFO   **main** DB Version: 0.21
11-08 11:33 DEBUG  database.db Start Database Thread: OK
11-08 11:33 DEBUG  database.db Checking DB Version
11-08 11:33 DEBUG  app    Create manga display: OK
11-08 11:33 DEBUG  app    Create toolbar: OK
11-08 11:33 DEBUG  app    Create statusbar: OK
11-08 11:33 DEBUG  app    Create system tray: OK
11-08 11:33 DEBUG  app    Show window: OK
11-08 11:33 DEBUG  app    Create notificationbar: OK
11-08 11:33 DEBUG  app    Window Create: OK
11-08 11:33 DEBUG  database.db b'SELECT \* FROM series'
11-08 11:33 DEBUG  database.db b'SELECT \* FROM series'
11-08 11:33 INFO   **main** Select defaultstyle: OK
11-08 11:33 DEBUG  **main** Create temp: OK
11-08 11:33 DEBUG  app    Checking Update
11-08 11:33 INFO   requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): raw.githubusercontent.com
11-08 11:33 DEBUG  requests.packages.urllib3.connectionpool "GET /Pewpews/happypanda/master/VS.txt HTTP/1.1" 200 25
11-08 11:33 INFO   app    Received version: 0.21
Current version: 0.21
11-08 11:33 INFO   app    Acceptable dropped items: 1
11-08 11:33 INFO   app    Unacceptable dropped items: 0
11-08 11:33 DEBUG  app    b"Dropped items: ['D:/Sadpanda/Genres/Vanilla']\n[]"
11-08 11:33 INFO   app    Adding dropped items
11-08 11:33 DEBUG  gallerydialog Triggered Gallery Edit/Add Dialog
11-08 11:33 DEBUG  database.db b'SELECT namespace FROM namespaces'
11-08 11:33 DEBUG  database.db b'SELECT namespace FROM namespaces'
11-08 11:33 DEBUG  database.db b'SELECT tag FROM tags'
11-08 11:33 DEBUG  database.db b'SELECT tag FROM tags'
11-08 11:33 DEBUG  misc   Instantiate CompleterTextEdit: OK
11-08 11:33 DEBUG  database.db b'SELECT \* FROM series'
11-08 11:33 DEBUG  database.db b'SELECT \* FROM series'

**Comment by twiddli** [comment]
is that everything?

**Comment by ghost** [comment]
yup

**Comment by twiddli** [comment]
And what happens when you click add?

**Comment by ghost** [comment]
i just dragged it to the window, should i try with the monitor feature

**Comment by twiddli** [comment]
No, i'd like to know about this specific method.
Currently, when you only drag one folder/file, it'll trigger the gallery dialog as if you're intending to add one gallery, but when you drag multiple files, it'll bring up a gallery list.

**Comment by ghost** [comment]
ah yeah, sometimes it does that, now it just never did and automatically accepted it

but when it does ask before adding, it's stuck on 35% :/

**Comment by ghost** [comment]
ops sry but ye ah, it didnt ask for it now but when it does, its at 35% constantly :/

**Comment by ghost** [comment]
this is with the monitor feature, instead of 35%, it's at 23% http://i.imgur.com/HluCUHp.jpg
its super weird because when i restart, i can see it definitely put more than 1/4 of my folder

**Comment by twiddli** [comment]
Can i ask you to populate in debug mode (and let it get stuck), and then provide me the debug log?
Earlier when you said that only 2-3 chapters could get imported; What did you mean?

**Comment by ghost** [comment]
if i drag them one by one, it works fine
heres debug, it freezes up now 

11-08 12:57 INFO   **main** Happypanda Version 0.21
11-08 12:57 INFO   **main** OS: Windows 8

11-08 12:57 DEBUG  database.db Checking DB Version
11-08 12:57 DEBUG  **main** Init DB Conn: OK
11-08 12:57 INFO   **main** DB Version: 0.21
11-08 12:57 DEBUG  database.db Start Database Thread: OK
11-08 12:57 DEBUG  database.db Checking DB Version
11-08 12:57 DEBUG  app    Create manga display: OK
11-08 12:57 DEBUG  app    Create toolbar: OK
11-08 12:57 DEBUG  app    Create statusbar: OK
11-08 12:57 DEBUG  app    Create system tray: OK
11-08 12:57 DEBUG  app    Show window: OK
11-08 12:57 DEBUG  app    Create notificationbar: OK
11-08 12:57 DEBUG  app    Window Create: OK
11-08 12:57 DEBUG  database.db b'SELECT \* FROM series'
11-08 12:57 DEBUG  database.db b'SELECT \* FROM series'
11-08 12:57 INFO   **main** Select defaultstyle: OK
11-08 12:57 DEBUG  **main** Create temp: OK
11-08 12:57 DEBUG  app    Checking Update
11-08 12:57 INFO   requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): raw.githubusercontent.com
11-08 12:57 DEBUG  requests.packages.urllib3.connectionpool "GET /Pewpews/happypanda/master/VS.txt HTTP/1.1" 200 25
11-08 12:57 INFO   app    Received version: 0.21
Current version: 0.21
11-08 12:57 INFO   app    Acceptable dropped items: 1
11-08 12:57 INFO   app    Unacceptable dropped items: 0
11-08 12:57 DEBUG  app    b"Dropped items: ['F:/Sadpanda/Genres/Test']\n[]"
11-08 12:57 INFO   app    Adding dropped items
11-08 12:57 DEBUG  gallerydialog Triggered Gallery Edit/Add Dialog
11-08 12:57 DEBUG  database.db b'SELECT namespace FROM namespaces'
11-08 12:57 DEBUG  database.db b'SELECT namespace FROM namespaces'
11-08 12:57 DEBUG  database.db b'SELECT tag FROM tags'
11-08 12:57 DEBUG  database.db b'SELECT tag FROM tags'
11-08 12:57 DEBUG  misc   Instantiate CompleterTextEdit: OK
11-08 12:57 DEBUG  database.db b'SELECT \* FROM series'
11-08 12:57 DEBUG  database.db b'SELECT \* FROM series'

**Comment by ghost** [comment]
mhm im testing it with different chapters and it loads fine, but on the chapters causing this bug, if i add those one by one, they load fine too..

o.o, everything is .cbz btw

**Comment by twiddli** [comment]
~~Would it be possible for you to send me these 'bugged files'? You can use an instant share service.~~
EDIT: Actually nevermind. An explanation of the folder structure inside the cbz's would be fine.
I just discovered a bug where archives with structures like this will fail:

```
top-folder
---\folder_in_top_folder
--------\img1_in_folder_in_top_folder.jpg
--------\img2_in_folder_in_top_folder.jpg
....
```

**Comment by ghost** [comment]
test
---\folder1_in_test
--------[artist]chapter.cbz
--------[artist]chapter.cbz
---\folder2_in_test
--------\tank_or_anthology
----------------[artist]chapter.cbz
----------------[artist]chapter.cbz
----------------[artist]chapter.cbz
---\folder3_in_test
--------\RAW
----------------[artist]chapter.cbz

**Comment by twiddli** [comment]
What about inside those cbz's?

**Comment by ghost** [comment]
just images, no folders or anything in it

**Comment by twiddli** [comment]
Welp, that's odd. Would it be possible to send me one of those archives then? You can email it: happypandabugs@gmail.com, or use any of the instant share services around the net. I'd need to inspect the archive myself.

**Comment by ghost** [comment]
my internet is too slow to upload multiple files ..
here are the ones i have, only thing i changed was the extension (zip > cbz)
http://exhentai.org/g/764318/539629b29f/
http://exhentai.org/g/825484/6db4dcad03/
http://exhentai.org/g/626032/56459b1bc6/
http://exhentai.org/g/763996/443323483f/
http://exhentai.org/g/694054/6f05319b27/
sometimes the uploader decides to put a txt file in it (http://i.imgur.com/NMEdbjh.jpg)

could this be the cause of it

**Comment by twiddli** [comment]
Maybe. I'll try them out, thanks.

**Comment by twiddli** [comment]
I have identified the issue. This will be fixed in the next update. Thank you for your help.

**Comment by ghost** [comment]
np, what was the issue?

**Comment by twiddli** [comment]
Importing issues should now be fixed in v0. 22.

**Comment by twiddli** [comment]
Considering this issue resolved.
