### ISSUE TITLE
Changing path of monitored folders?

### ISSUE THREAD

**Issue by UnlimitedArk** [Pewpews/happypanda#185]
I know this version of HP isn't really supported anymore, but i have to ask :
up until now i had my manga folders on an external hdd, but now that i want them on the main drive i have no idea on how to change the path of all the added galleries

Do i have no other option besides having to readd all galleries from scratch (thus losing any tag edits and such i may have made) even if only the drive letter changed?

Also on the subject of tags, is there any way to delete tags from the "ns & tags" list, so that i can start over? (some old tags are still there even if no galleries has them, very untidy)

**Comment by twiddli** [comment]
>Do i have no other option besides having to readd all galleries from scratch (thus losing any tag edits and such i may have made) even if only the drive letter changed?

HP will detect if a gallery is moved from a 'monitored' folder (`settings->application>monitoring`) and will ask if you want to update the gallery's path inside HP.
I don't know how many galleries you have or how your folders are set up, but you could:
1. add the root folder to the monitored folders list
2. move the galleries, update the paths in HP one by one (obv. very cumbersome if you have alot of galleries)

If this method seems infeasible, read the better solution below.

>Is there any way to delete tags from the "ns & tags" list

Unfortunately no, I didn't get to implement that. This will, however, be possible in HPX. But fret not, there is a way.

**Recommended approah:**
Kill two birds with one stone.
1. Go into `settings->advanced->database` and export your database
    - This will export all your galleries' metadata (tags, read count, date added, last read, etc.) for later retrieval
2. Move your galleries to the new drive
3. Close HP and delete (backup) everything in the `db` folder at your HP installation. (`thumbnail` folder and `happypanda.db`)
4. Open HP and a new database file will be created
5. Import all your galleries from the new location
6. Lastly, go back to `settings->advanced->database` and import the `.hpdb` file.

**Comment by UnlimitedArk** [comment]
Damn, thanks for the fast response.
Unfortunately as soon as i click export database it goes "it was too big, critical error", so i guess i'll have to transfer them one by one or just leave them where they are for now.

Truth to be told, even if have close to 2k galleries, not many of them have tags or any other relevant metadata (just a few that i bothered tagging), so i could actually just readd them from scratch for this time (bit of a pain in the cases where i changed the thumbnail cover maybe?)

So it's mostly a problem for a future in which i have the same problem, but maybe with double the gallery count and all of them tagged, i just hope i'll be able to export the metadata in that case.
Cheers anyway.

Edit: for some reason, while hp does detect renaming and thus ask if i want to edit the path, it doesn't recognize deletion or plain moving, so i can't really move one by one even just the ones i want to save the metadata of. Guess i'll just leave it as it is for now

**Comment by twiddli** [comment]
are you on the latest HP release?

**Comment by UnlimitedArk** [comment]
Yep i'm on 1.1, i also had a backup of 0.30 and i just tried to see if that one could export the database, but nope

**Comment by twiddli** [comment]
oh, sounds weird, could you open the log file and CTRL+F 'critical' to see what the error was?

**Comment by UnlimitedArk** [comment]
Oh now i see fom the log what the problem, was, basically it encounters a critical error every time it doesn't find a folder

19-04 01:15 CRITICAL app    <class 'FileNotFoundError'>: [WinError 3] The system cannot find the path specified: 

Basically the problem are some vncg galleries which in the past i guess i deleted or renamed, but with the gallery still on HP
The critical error was instant because a gallery which such a problem started with "a"
Now i'm cleaning out all of them and the export seems to make progress until it finds another one

**Comment by twiddli** [comment]
additionally, you can filter out galleries that do not exist anymore with this term: `path:none`

**Comment by UnlimitedArk** [comment]
Unfortunately it was some sneaky galleries which didn't get revealed with that specific term, basically HP believed they were still there, but upon opening it was indeed "it doesn't exist", so i think it was a matter of me poorly cleaning out and maybe not updating paths when requested

After deleting those out, it managed to complete the export (vastly appreciated the fact that if it encountered an error, it didn't start over the following try, really helped when the last error was at 98%) 
Now i just followed your very first recommended approach, and i guess i'm all good, tags and favs are all there (i just have to change again some thumbnail covers, but that's minor stuff that i can easily avoid if i just bother to make the cover the first file in the gallery)

Thanks a whole bunch, can't believe i stumbled on not checking the log and was gonna lazily leave it as it is (alongside future problems)
