### ISSUE TITLE
How to set which site to check first when auto fetching metadata?

### ISSUE THREAD

**Issue by YukiSakuma** [Pewpews/happypanda#187]
When auto fetching metadata the first site it will check for metadata is eh/ex but I need to change it to chaika first, I've tried changing it in the settings.ini but no effect.

**Comment by twiddli** [comment]
Hi, that's not possible, sorry. You can force it to fetch from chaika if you apply a chaika URL on the gallery.

**Comment by YukiSakuma** [comment]
Well, that's unfortunate because if I have a bunch of galleries from chaika it would be tedious to manually add them. oh well.

**Comment by twiddli** [comment]
I'm not sure I understand. If the gallery is on chaika and not on EH (which is generally the case?), it should automatically look up on chaika too after failing a lookup on EH. Make sure you have it enabled. (*`Settings->Web->Metadata`* at the bottom)

**Comment by YukiSakuma** [comment]
Yes it is enabled but I want to autofetch it on chaika first because checking on EH first takes considerably an amount of time especially if you autofetch a ton of galleries at once that you downloaded from chaika.

**Comment by twiddli** [comment]
Oh I see, Sorry, you'll have to wait for HPX.
