### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Drauthix** [Pewpews/happypanda#188]
Good day, people! I'm having problems starting HP. I hope someone can help me with this. My apologies if this is a known problem or if i'm at fault (I used the search bar in the open and closed issues but I didn't find anything, and even asked in other two places before).

OS: Mint 18.2 (Ubuntu 16.04.2 iirc)

1st  Installed python-pip from repositories "sudo apt-get install python-pip"
2nd Installed HP from PYPI "pip install happypanda"
3rd Running HP "happypanda --home"

And after the third command I get this;

Traceback (most recent call last):
  File "/home/drauthix/.local/bin/happypanda", line 7, in <module>
    from happypanda.__main__ import main
  File "/home/drauthix/.local/lib/python2.7/site-packages/happypanda/__main__.py", line 130
    if msg_box.exec() == QMessageBox.Yes:
                  ^
SyntaxError: invalid syntax

Sorry for my bad english, I hope someone can help me with this problem. Thanks in advance.

**Comment by twiddli** [comment]
You're using Python 2.
HP requires Python 3.
Use `pip3` not `pip`.
Install `pip3`: `sudo apt-get install python3-pip`.
Then use `pip3` to install HP: `pip3 install happypanda`.

Note:
Uninstall the previously installed HP like this: `pip uninstall happypanda`

**Comment by Drauthix** [comment]
Oh! thank you very much. It's working now, sorry for being so slow, people keep telling me to stay away from computers but I just don't learn. Have a nice day~
