### ISSUE TITLE
Increase minumum height of the scroll-bar

### ISSUE THREAD

**Issue by Black-Light** [Pewpews/happypanda#21]
This might not be as big of a problem on low-res screens but on my 1440p screen the scroll-bar just becomes difficult to grab with the mouse.

**Comment by twiddli** [comment]
Thanks for the report. It'll be fixed in the next update.

**Comment by twiddli** [comment]
You can actually quite easily change the height of the scrollbar yourself (assuming we are talking about the vertical scrollbar). In the folder where Happypanda is resided, look for _style.css_ in the _Res_ folder.
In here you change the value of `min_height` _(to something like 100px)_ of `QScrollBar::handle:vertical`.

**Comment by twiddli** [comment]
resolved in version 0.22
