### ISSUE TITLE
[Request] After finding more galleries through the folder watch, instead of prompting for every single gallery move/show them in a Recently Added filter

### ISSUE THREAD

**Issue by HASJ** [Pewpews/happypanda#37]
I just dropped about 100 items on the folder and after HP was done processing them, I had to click "Yes" in every single prompt and then "Done" in the following metadata.
That's 200 hundreds clicks. Taking 4 seconds to conclude and item's addition, that's 800 seconds. For something that is essentially gonna always happen (confirming whether the gallery added to the watch folder is something you want or not).
The way it is now, I can't let HP go through my whole collection. I just don't have the patience to do 1500 clicks in 100 minutes.
I don't think HP watches for changes in manually added galleries, even if they are on the watch folder.
That's where the Recently Added filter comes in. You can just check later if there is something wrong and fix it separately, instead of wasting (a lot of) time on HP.

**Comment by twiddli** [comment]
> I don't think HP watches for changes in manually added galleries, even if they are on the watch folder.

Could you elaborate please?
When your galleries are in a monitored folder, you'll be notified if you for example rename the gallery file or move it (akin to deleting). Well that's what _should_ happen anyway.

The prompts will need a little bit more work, yes. I had already thought of the scenario where a lot of files were moved to a monitored folder while implementing this feature. To answer this, I've thought of making it wait a little bit before showing a prompt in case more galleries were found. If more galleries were found within that short time, a prompt showing all those galleries would've been shown instead. That way you only click _yes_ once for all of them.

**Comment by HASJ** [comment]
> > I don't think HP watches for changes in manually added galleries, even if they are on the watch folder.
> 
> Could you elaborate please?
> When your galleries are in a monitored folder, you'll be noticed if you for example rename the gallery file or move it (akin to deleting). Well that's what should happen anyway.

Yes, you're right. Works even better if I set imported galleries to be moved to the watch folder.

**Comment by twiddli** [comment]
Feature is in the plannings in #63 so I will close this one.
