### ISSUE TITLE
Do a similarity check on artist names

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#40]
i noticed tags are clickable to auto search for the tag you clicked, wish that artists would also work this same way.

at the same note there should be a way to compare artists after the name saved for example if some has typos and so on.

**Comment by twiddli** [comment]
> i noticed tags are clickable to auto search for the tag you clicked, wish that artists would also work this same way.

This feature is coming in the next version as part of the redesigned gallery window. The artist field will be clickable and will search the artist for you. 

> at the same note there should be a way to compare artists after the name saved for example if some has typos and so on.

Do you mean a _similarity_ check on artist names? Or do the names have to be exact but might differ in upper/lower cases?

**Comment by CuddleBear92** [comment]
both maybe?
similar in general really as uploaders might have names wrong and so on.
also thought on the artist names, how about having subnames for them aswell like how some have more than one name or is names with different names at times.
as example  have on the top of my head is askray=bosshi for example and it would group all the releases from both these under the same artist name for example.
this way artists could have more than one user name but it would still all be connected to each other.

**Comment by twiddli** [comment]
> i noticed tags are clickable to auto search for the tag you clicked, wish that artists would also work this same way.

Implemented in v0.26

I don't think anything else from this issue will get implemented. Closing it.
