### ISSUE TITLE
Gallery type colors and tags colors

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#41]
for example if an issue has an uncen tag the area around the issue would be colored with a color connecting that.
the same could be done with other tags that the user chooses. 

i saw the Gallery Type colors in your Roadmap but i think those are so few that they could have small icons instead and let colors be a tag thing maybe?
how many gallery types is there really that colors would need to be used?

on the comment on tags, if you dont want to use colors that way then it could be setup that important tags (that the user chooses) would be shown as a standard view instead of using the tooltip and so on.

**Comment by HASJ** [comment]
If I'm not mistaken, this is a planned feature. Check the wiki.

**Comment by CuddleBear92** [comment]
as i commented on, the roadmap does contain Gallery Type Colors and the ability to choose the color.
not tags as i made this issue for.
i dont think Gallery Types needs to use colors as they could use an icon of some sort, but there is loads of tags no matter how big your collection is and would make use of colors much better IMO.

it all in all would be better to be able to color code the tags the user really likes and their fetishes.
for example i would set all uncen tags for a color that is bright and maybe a few few others. but it would not stop people to use more than a few either i guess.

ofc doing colors would be hard aswell if an issue had more than one tag that needs to use a color for example. 
something like that could have used colors for how many tags that fit the users fav slots (like if there is only one tag that the user have colored it would use that one, if there was two then it would use both colors in a split view maybe. if there was say 3 or more it would use bronze, silver and gold for example if it has loads of tags)

just small examples tho, but i dont think Gallery Types needs colors and could be used better for fav tags and fetishes people have.

**Comment by twiddli** [comment]
Your suggestion sounds interesting and useful, though I'd imagine that some people would prefer galleries to be colored based on type instead. I'll take both up to consideration and maybe find a solution for both? But in any case.. this is something that will first happen when I start working on the _Visual_ section in settings.

**Comment by CuddleBear92** [comment]
i don't mind both at all, but i would love to have certain tags in certain colors for sure as it would cater for pretty much anyone no matter what they like and it would make it easier for people to get what they want out of their program/collection.

this would pretty much turn every happypanda server into a color painting of their own fetishes XD

**Comment by HASJ** [comment]
You know, this reminded me of EH Plus, an userscript for ExH that, among other things, allow for this to happen.
Here's an example:
![EH Plus](http://i.imgur.com/AI0Bqzd.jpg)

It automatically fades visited galleries and if you have the tag flagging hath perk, you can do that on the screenshot.
Damn, I wish I knew how to code just to help you Pewpews!

**Comment by twiddli** [comment]
Feature will include:
- Ability to customize which type/tag is shown with which color

**Comment by twiddli** [comment]
Gallery type colors implemented in 716a013613da1b618ff28444ebd90b6d36b16ef4
Gallery tags colors won't be implemented but instead a kind of smart list (like those smart playlists in various music applications) might be implemented which can then be configured to filter select tags.
