### ISSUE TITLE
Tag wordcloud based on your server/client?

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#42]
how about a wordcloud of all the tags in your server?
somewhere you can browse your tags, add a tag or more to a seach and so on.
also favorite different tags would be nice https://github.com/Pewpews/happypanda/issues/41

if something like that would be smooth then you could add it as a side menu to easily add and remove tags in the search the user is doing (think booru searches think http://gelbooru.com/ seaches where you can add and remove tags to the search with a click)

**Comment by twiddli** [comment]
> how about a wordcloud of all the tags in your server?
> somewhere you can browse your tags, add a tag or more to a seach and so on.

Have you seen the DB Overview window? It's located in _Settings_ -> _About_ -> _DB Overview_ tab. It's very limited atm. but it let's you see all your namespace & tags, and it even let's you search with them (right click to open context-menu). It's a very handy window if you don't know what to search for. I think I'll make it accessible from the toolbar too.

**Comment by CuddleBear92** [comment]
no i didnt see it as its a bit hidden away for normal use.
if the list like that would be more of use with normal usage then i think we need to track the amount of that tag there is aswell as be able to sort by amount.

something like that should also need subtags maybe, where the user can use subtags to mean one tag
for example that a tags that means the same are placed inside a shared tag where all the subtags that mean the same thing is also places. searches for the main tag aswell as all the subtags should then give the same mangas/issues.

ofc subtags should be defined by the user themselfs (maybe with help from the taglist)

**Comment by twiddli** [comment]
> how about a wordcloud of all the tags in your server?
> somewhere you can browse your tags, add a tag or more to a seach and so on.

_DB Overview_ fits the description, and the only way to add a new tag should be through a gallery.

> if the list like that would be more of use with normal usage then i think we need to track the amount of that tag there is aswell as be able to sort by amount.
> 
> something like that should also need subtags maybe, where the user can use subtags to mean one tag
> for example that a tags that means the same are placed inside a shared tag where all the subtags that mean the same thing is also places. searches for the main tag aswell as all the subtags should then give the same mangas/issues.
> ofc subtags should be defined by the user themselfs (maybe with help from the taglist)

Can you create new issues for these suggestions?

**Comment by CuddleBear92** [comment]
made them: 
https://github.com/Pewpews/happypanda/issues/65
https://github.com/Pewpews/happypanda/issues/66

**Comment by CuddleBear92** [comment]
final thoughts, i think something like a tag sharing function might be needed for something like this tho, hydrus hosts his own server for this thing..... unsure how else it can be done TBH.
maybe hosted on your site? the file size shouldnt be too high for such things but....

**Comment by twiddli** [comment]
Exporting and importing of gallery metadata is a feature implemented in v0.26 which can be used for sharing metadata. I don't see how sharing tags would be useful when you can already fetch metadata for most galleries through ex/g.e (and more to come).

**Comment by CuddleBear92** [comment]
i guess thats true.... just used to it being really handy in Hydrus, but tags might be missed on those sites tho. then again, they are really rare and far between i guess. atleast comparing to images from a booru... fine i do agree it might not be needed. a tag export/update function with an import function would do alot of this too tho (then it could be used as a backup aswell)

**Comment by twiddli** [comment]
Exporting and importing of individual gallery metadata is coming soon too..
