### ISSUE TITLE
when the screen setup is changed, HappyPanda opens on the no longer used screenspace. 

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#47]
when the screen setup is changed, HappyPanda opens on the no longer used screenspace. 
might have just been a one time deal there but when i removed one of the screen on my setup to have my main screen mirrored on a tv it tried to open where the last location was.... on the other screen space outside the one i have ATM.

**Comment by twiddli** [comment]
Is this issue only true for Happypanda? Did other programs open up correctly?

**Comment by CuddleBear92** [comment]
yeah, never have issues like this with other programs at all.

**Comment by twiddli** [comment]
Alright, I've (hopefully) pinpointed the cause. Expect a fix in the next version.
