### ISSUE TITLE
High DPI/4K Support?

### ISSUE THREAD

**Issue by TheJoe49** [Pewpews/happypanda#67]
If you have the time and it is easy enough could you add the support. I am finding it next to impossible to use happypanda with my computer.

**Comment by twiddli** [comment]
Sure, I'll look into it.
Could you specify the impossibilities you're experiencing in more detail?

**Comment by TheJoe49** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/16162727/11634169/9c1b74ee-9cd4-11e5-9c23-a3eb409aa58c.png)
So I am looking back at what I said and impossible may have been a little too dramatic, its just difficult to use.

**Comment by twiddli** [comment]
That looks pretty bad, yeah..
I'll definitely try fixing it. Sorry for the inconvenience.

**Comment by HASJ** [comment]
Holy shit. Didn't think I needed a 4K display but, I do.

**Comment by TheJoe49** [comment]
Its okay, totally not your fault.

**Comment by edgar1016** [comment]
Yeah I'd appreciate the 4k support as well don't worry about the inconvenience considering 4k still isn't common mine doesn't seem to be as bad, though some of the thumbs I can't see like the top left one. Out of curiosity what's your scaling set to Joe?
![2015-12-12 10 27](https://cloud.githubusercontent.com/assets/13511581/11763137/2488097e-a0bc-11e5-821e-04921c9ed19e.jpg)

**Comment by twiddli** [comment]
You guys can try deleting the contents _(not the file)_ of the `style.css` file found in the **Res** folder. Please let me know if it helps.

**Comment by edgar1016** [comment]
It fixed some of the GUIs they load properly but are harder to see all white text and backgrounds the toolbar seems smaller i'll keep playing around with it and await an official release there's no rush I can still use it.
Edit: So I lost the original style.css content so I copied and pasted the one from version 0.20 I had and it's seems to fix some issues like the Favorite and Library tab as well as the GUI loads better. also updated the photo to show what it looks like after using the 0.20 style.css
![image](https://cloud.githubusercontent.com/assets/13511581/11763307/401ab910-a0c2-11e5-948e-9e593da0f01e.png)

**Comment by twiddli** [comment]
Could you do me a favor and copy-paste the contents from [here](https://raw.githubusercontent.com/Pewpews/happypanda/alpha/res/style.css)?
Please post result.

**EDIT:**
[Here](https://github.com/Pewpews/happypanda/blob/alpha/res/style.css) is the most up-to-date

**Comment by edgar1016** [comment]
Here's what I got with the new code.
![2015-12-12 13 51](https://cloud.githubusercontent.com/assets/13511581/11763833/bd84db32-a0d7-11e5-99cf-6a2befd586a6.jpg)

**Comment by twiddli** [comment]
Are the buttons and scrollbar the right size, you think?

The toolbar and statusbar have a hardcoded size, they will be updated in the next version. The icons and gallery thumbnails will also get updated.

**Comment by edgar1016** [comment]
Yeah the scroll bar is better the buttons are fine as well thanks looking forward to the next update.
