### ISSUE TITLE
Cant get CDisplay (external viewer) to work.

### ISSUE THREAD

**Issue by SgtWiking** [Pewpews/happypanda#69]
Was trying to get CDisplay to work with the gallery manager, as its the program I use most for viewing .cbr and .cbz archives.
For some reason if I run it through your Happypanda, it only opens the first page of comic/manga, and I cant switch to any other pages in the archive. While opening same .cbz file using default viewer through Happypanda lets me scroll through all the pages.

Its a bit strange behavior, and I probably missed something, so any help would be appreciated.
Till that gets figure out I can still use "Show in Folder" option, and manually run the archive.
Cheers, keep up the awesome work!

**Comment by twiddli** [comment]
Specify the path to the CDisplay executable in _Settings_ -> _Application_ -> _General_. 
Then disable the `Extract archive before opening` option in _Application_ -> _Gallery_

**Comment by SgtWiking** [comment]
Tried it, still the same problem:
1. Extract Archive before opening - OFF
https://i.gyazo.com/058337e35730d4d77e82e1b798057b80.png
2. Path set to CDisplay
https://i.gyazo.com/1e4abe7f3f2a6b58db57aea36be81396.png

Restarted the program a few times just in case, still only opens first page in CDisplay, instead of the entire .cbz archive. Did I miss another setting?

**Comment by twiddli** [comment]
Looks like you're using an older version. Could you update to the latest?

**Comment by SgtWiking** [comment]
Updated to newest (0.26a), made a clean install, added the archives again, Extract to OFF, Path to CDisplay. Still only extracts and opens the first page in whatever viewer I'm using, instead of running/opening the entire .cbz file through whatever default program I setup in windows.

**Comment by twiddli** [comment]
Alright.
Please try opening a gallery while running Happypanda in debug mode.
Happypanda can be run in debug mode by adding the `--debug` argument when launching Happypanda.
From the cmd run Happyanda like this: `Happypanda.exe --debug`. 

When done, please provide the file named `happypanda_debug.log` which was created and I'll take a look at it.

Another thing I want you to do is, after having closed Happypanda (to clear the temps) and then opening it again, try opening a gallery and then immediately after, go check if a folder was generated in the folder named `temp`. If true, please check if all pages are present.

**Comment by Exedge** [comment]
Try using irfanview, it works fine and it's a great viewer.  This problem also happens with windows 10's photo app.

**Comment by SgtWiking** [comment]
Sorry for late reply, was quite busy these days with Holiday stuff.
Switched to PandaViewer to check it out, turned off unpacking there, and when I double click a .cbz archive it opens it in default windows program CDisplay.

I'll see about getting you a --debug .log file for Happypanda soon, sorry for the delay.
