### ISSUE TITLE
Populating database ceasing function

### ISSUE THREAD

**Issue by Bozunee** [Pewpews/happypanda#70]
At random times after designating a group of archives or folders the "Populating database" phase will stop at a low percentage, usually at around 15% or 18% occasionally.
Not sure what is going wrong as I've had this happen multiple times with smaller gallery preparation requests (less than 200) as well as large ones (1000+).

One thing I want to note is that even though the status bar is fully animated and seeming to be doing something, the happy panda window is fully functional and can open other galleries.
![Example image](http://puu.sh/lWYnD/dfb7eecc7f.png)

**Comment by twiddli** [comment]
The window should be disabled during the whole process.
Can I check your `happypanda.log`?

**Comment by Bozunee** [comment]
Sure 
The file was named happypanda.log.1
http://puu.sh/lYRiT/bc47d9fa13.1

**Comment by twiddli** [comment]
Alright, I've looked through your log.
Seems like some exceptions are being raised when a corrupt file is found which interrupts the process.
That explains why it hangs before finishing.

These are the the files containing bad files:
`Comic LO 2012-04 Vol. 97.zip`
`[Fujisaka Lyric] FEVER! Pack'n Co (Complete) [English] {Mistvern}.zip`
`[Hazuki Shishimaru] Amaetai Fucks [English].zip`
`[Gambler Club (Kousaka Jun)] 3-A 4 (Mahou Sensei Negima!) (English).rar`
`(C77) [Aneko no Techou] A Certain Pair of Kurokos Electric Panties (To Aru Kagaku No Railgun) [English].zip`
`[Yahiro Pochi] Lovematio - So Lovely Irrumatio (Complete, English) {doujin-moe.us}.zip`

This one isn't corrupt but is compressed with a type not supported:
`[Hyocoro] Dinner between the Flower and the Pig.zip`

Are these real archives? If so, then they're most likely corrupt:
`(C77) [French letter (Fujisaki Hikari)] Pedoria 1 2 Princess Remilia Scarlet (Touhou Project) [English].zip`
`(C81) [16000 All (Takeponian)] Y (Touhou Project) [English].zip`
`(C82) [Kikurage-ya (Kikurage)] Watashi Ki ni Narimasu!! (Hyouka) (English).zip`
`[Ookami Uo] I Tried To Get JS & JC On Camera (English)[5 a.m.].rar`
`(æˆå¹´ã‚³ãƒŸãƒƒã‚¯) [ãƒãƒ³è²´èŠ±ç”°] å®¶æ”¿å©¦ã¨æš®ã‚‰ã™100ã®æ–¹æ³• Vol.01.rar` (yeah, that's what it says)
`[æ¡œå°é‰„] ãƒ¡ã‚¤ãƒ—ãƒ«ã‚·ãƒ­ãƒƒãƒ—.zip`
`(C85) [TORA MACHINE (Kasukabe Taro)] Yami Ochi Game (To LOVE-Ru) [English] {doujin-moe.us}.zip`

Something weird is wrong with these archives:
`(æˆå¹´ã‚³ãƒŸãƒƒã‚¯) [ã¸ã‚“ã‚Šã„ã ] å¦¹â˜†ã“ã‚“ã¨ã‚ãƒ¼ã‚‹ å…¨3è©±.zip`
`[Gambler Club (Kousaka Jun)] 3-A 4 (Mahou Sensei Negima!) (English).rar`

Try moving those archives outside the folder.

The exceptions will be suppressed and the user will be notified of the bad files in a future version.

**Comment by Bozunee** [comment]
After investigating a bit more, the "bad" files in the first list I found were just incomplete downloads I moved into my main folder after starting up the torrenting process, so those were errors on my part.

Regarding the second file, would there be a chance for the compression type to be supported in a future version?

The last list, the first two .zip files were intact with the rest being corrupt, no idea what happened with the messed up filename, as it should be displayed as this.
(成年コミック) [ポン貴花田] 家政婦と暮らす100の方法 Vol.01.rar

Guess a solution would be for happypanda to skip any corrupted files and add them on that skipped list with a possible tag showing their corrupted state.

**Comment by Exedge** [comment]
I have been having similar problems as well. It has to do with the character set the database (or more accurately the program) can handle. if possible it should be made so that it has compatibility with unicode. however i would recommend changing the file folders and metadata to match. that will make it far easier to search.

**Comment by twiddli** [comment]
> Regarding the second file, would there be a chance for the compression type to be supported in a future version?

I rely on a package provided by the python standard library to handle zip archives. Adding support would have to be done by the authors of that package.
