### ISSUE TITLE
Metadata getting removed

### ISSUE THREAD

**Issue by Exedge** [Pewpews/happypanda#72]
For some reason, nearly all of the metadata has been removed from most if not all of the files. The main issue seems to be in the tag area, especially the misc section which has been removed entirely. the artist and parody tags at least remain. this change happened after i had removed some galleries and there files that were returned from a search. hopefully this info helps.

This is a big issue as it can severely affect the search-ability of the database.

**Comment by twiddli** [comment]
Are you talking about metadata disappearing from galleries in your Happypanda library?
If so, a fix (hopefully) has already been made in the _alpha_ branch. See b5cba7507cfba75cf5a0acbaabea8e0615a8b5c8.
You can choose to run from source with the code in the _alpha_ branch if you can't wait for the next version.

**Comment by Exedge** [comment]
It seems that I still get the problem. I think it has to do with how it removes data from the database. specifically for me, when you delete the folders as well. I think It might have something to with how it updates the database. I assume that the database has to change the indexes down when folders are removed so maybe that has to do with it.

**Comment by twiddli** [comment]
Hmm.. Could you please describe the problem in more detail? I haven't really understood it yet.
And could I take a look at your log?
