### ISSUE TITLE
Cannot add more galleries

### ISSUE THREAD

**Issue by Shakiga** [Pewpews/happypanda#74]
Sometimes happy panda stops adding more galleries even when I have tried all the add galleries function. 
My current happy panda instance has 168 galleries and this number doesn't go up after I add more. It simply doesn't do anything after I chose the gallery to add.  Reset happy panda doesn't work.

[happypanda_debug.log.txt](https://github.com/Pewpews/happypanda/files/82214/happypanda_debug.log.txt)

**Comment by twiddli** [comment]
Hi 
What do you mean by 

> Reset happypanda doesn't work 

How did you reset? 

And also, I'm pretty sure the database issues I have fixed for the next version covers your issue. I'll have to ask you to wait for the next version.

**Comment by Shakiga** [comment]
Oh I see, thanks for your work!

By reset I meant wiped the database clean. Sorry for the confusion.

**Comment by twiddli** [comment]
Please check if the issue has been fixed in the newest update.
I'll re-open if the issue still persists.
