### ISSUE TITLE
A way to filter multiple artists in gallery list

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#78]
i noticed the new and really great function of having all our artists listed. 
but we cannot favorite out artists just yet.
would be nice to be able to do so, and when the time comes for subscriptions you could let the user auto check for new issues of those artists and let them download them on the spot. 

when the list gets longer and longer it gets harder to get to the content you want. favorite tags and artists is the way to go IMO.

**Comment by twiddli** [comment]
Hi, what do you mean by _download them on the spot_?

An improvement will be made to the gallery list filters that will allow more something like this.

**Comment by CuddleBear92** [comment]
just thinking if subscription downloads ever became a thing it could also use the favorite list.
think how hydrus handles subscriptions http://hydrusnetwork.github.io/hydrus/help/getting_started_subscriptions.html

get a tag (in this case the artist favorites) and check for new entries on the sites.... i need to make an issue about subscription downloads tho.

**Comment by twiddli** [comment]
Forgot to update this issue.
With the release of [v0.28](https://github.com/Pewpews/happypanda/releases/tag/v0.28-alpha) it became possible to use regex in gallery list filters. With regex enabled, you can filter out multiple artists like this: `artist:(artist1)|(artist2)|(artist3)`
