### ISSUE TITLE
Improve the parser to extract languages better

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#79]
seems the field does not get filled out (the one in the edit menu of the issue) 
eventho the issue might have the right language tag either in the tooltip window it does not show there.
also, filename parsing should look for [english] [eng]- (english) (eng) english aswell as eng if you are not already parsing it that way aswell.... for those cases the tags are lacking inside the file or online.

**Comment by twiddli** [comment]
I plan on taking a look at the filename parsing and overall parsing of gallery names sometime in the future. Something like this will get fixed then.
