### ISSUE TITLE
Change filetype icon in grid view

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#80]
i dont think how the filetype icons work is quite right.
right now it does use the icon for the default program you have set for that filetype.
for example i get the winrar icon on the cbz files, its all fine that i want to open those that way when in windows exporer and such but it doesnt fit in HP with that icon IMO.

i think it should be changed to text with another font or make a small logo for the common icons like cbz, cbr, zip, rar, pdf and folder gallery (dont recall if HP supports it but i dont use it)

the icon function itself is nice but it doesnt say what format it is, only what program its set as a default.

**Comment by twiddli** [comment]
I'll look into it.
