### ISSUE TITLE
enable deletion of files with the delete button.

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#81]
i dont know why this isnt in here yet but i think its really needed. its alot faster to just hit delete on the keyboard than to right click navigate to remove wait for the menu to open then click remove and delete.

if you are worried about leaving the options out then i think you could set those in the settings so the delete button only does the thing the user set it to.
an option to remove the confirmation is also needed, tho i would want it there myself.

**Comment by twiddli** [comment]
This was actually something I wanted as well but didn't bother to do because of the amount of code I had to change. 

I'll eventually add it sometime once I'm motivated.
