### ISSUE TITLE
group manga in folders?

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#82]
i think we should be able to group manga in folders.
this is mostly for artists, but could be used for series aswell (that is split up in chapters) 
think about how comicrack does it with its stacks.
it can use any metadata and pull the similar ones into stacks.
things i think will work with this, artists, convention (comiket and so on), tags (so everything with each tag will stay together (issues ofc should be in alot more than one folder at a time in this case)), series, parody/IP.

these folders should also be able to be sorted by amount of issues inside them for example aswell as alphabetically and any other sort we have.

**Comment by twiddli** [comment]
I plan on adding sorting options to sort by conventions or series in addition to #28.
Grouping several galleries together is what #28 will allow us to do.

**Comment by twiddli** [comment]
Closing this since it was a duplicate.
