### ISSUE TITLE
ignore certain formats in monitor folder

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#83]
since not everything is supported by all download programs like move on completion (HDoujin Downloader) i think we should be able to set certain limits on what gets imported.
for example setting it to only import cbr/z files or whatever the user sets it to. 

reasoning behind this is that many downloaders does download folders and images then converts them and deletes them afterwards. i just dont want these folders and loose files to be imported, only the finished product in an archive.

**Comment by twiddli** [comment]
Ignoring file extensions and folders will get added in the next version.
