### ISSUE TITLE
when changing windows size it also changes the position on your list. 

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#85]
i notice when you resize the window of the program it will move up or down the list depending on how you resize. would it not be better to let it auto jump to whatever you had highlighted?
i think this is for the better but i might be wrong. 
this is a small thing and is only for consistency more than anything else.

**Comment by twiddli** [comment]
I don't really understand this issue. 
Could you take a screenshot of it or something similar?

**Comment by CuddleBear92** [comment]
you can do this yourself, hard to explain with screenshots.
say if you scroll down and have an issue highlighted and you resize your screen (for example from full screen to half screen) it will move down the list bellow what you already had highlighted. i think it should try to show highlighted when it can when you resize the screen. 
also when it comes to what is visible with highlights. if you use your arrow keys to move up or down in your list the screen will not follow the highlighted issues. meaning you highlight things that you cannot see.
i think the screen should be moving with the highlighted issues.

**Comment by twiddli** [comment]
> list

I assume you mean in the grid view?

> issues

And this is galleries, right?

Are you talking about how the highlighted gallery jumps around (and sometimes out of view) when resizing the window?
If so then that's a very minor annoyance that I think isn't worth wasting time on.
