### ISSUE TITLE
sync with temp folder?

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#87]
if syncing back from the temp folder into the archive could be done it would be great.
say if you open an issue in an external viewer like an image viewer, you could delete pages/images in those viewers and that would delete it in the temp location aswell.
if that could be synced (pretty much make a new archive with everything in the temp folder (needs to contain everything for metadata files) then those pages/images would be deleted from the archive aswell.

real handy as many might like to remove things like white pages, black and white pages of the cover and ofc fan pages (where they say who translated it).
since all of these extra things are on a personal level then deleting it as you read it would be for the best IMO. 

something like this would need an archive manager that handles zipping up these files again.
and ofc filenames and folders should stay the same, practically replacing the one you had.
only one thing that might have to be looked into is success rate for making those. 
if one of those images dont follow suit then the page will ofc be lost.

**Comment by twiddli** [comment]
Sounds very out of scope and something that'll take a fair amount of time to make work well.
