### ISSUE TITLE
sorting doesnt handle empty field expectidly 

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#89]
i feel the sorting function in the list view does not work as expected.
for example sorting links. i would expect that the links would be sorted in one corner and if there is no links they would gather on the other side of the list.
yet i find that my link looks like this:

![](http://i.imgur.com/hY3eTst.png)

as you see there is empty fields all over the place and they are not sorted as expected.
this also happens to every column and it seems like sorting doesnt work at all really.

**Comment by CuddleBear92** [comment]
after more testing i find that nothing with the sorting really work sadly, should be looked into.

**Comment by CuddleBear92** [comment]
never mind, seems like it handles things correctly after doing a restart of the program. 
should not be the case to IMO.

**Comment by twiddli** [comment]
I plan on reworking the table view, see #59.
