### ISSUE TITLE
how do i monitor folders :(

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#9]
takes uber long to import them one by one and is the only way to fetch metadata by getting the ex link?

**Comment by twiddli** [comment]
Currently the only ways to quickly import is either by choosing 'Populate from folder' or 'Add galleries'.
When populating from folder you choose the top-level folder containing all your galleries and it'll add them all. Before adding to DB a list will popup where you can check which ones to add.
Choosing the latter will open a dialog list where you're supposed to keep adding your galleries (which can be from different folders) to the list and then add them to the DB.

Already existing galleries are skipped in both methods. The only way to add an already existing gallery is by adding it individually.

_"How do i monitor folders"_
This feature is not yet supported and was planned to be implemented in a later version (possibly 0.17).

_Is the only way to fetch metadata by getting the ex link?_
Yes, that is unfortunately the only way atm.
I am however thinking about improving and implementing auto-tagging features for the next version, so stay tuned!

**Comment by twiddli** [comment]
Folder monitoring: Implemented in v0.17
Auto metadata fetcher without ex link: Implemented in v0.17
