### ISSUE TITLE
Add a color wheel for hex colors

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#90]
i think some newer users might have issues with the hex color codes in the settings menu.
i think you should atleast have a link to a site that handles generates a code for them or embed it into the program.

**Comment by twiddli** [comment]
It isn't really hard to google for hex colors... 
Though I understand why a color wheel would be useful for those with limited internet.

**Comment by CuddleBear92** [comment]
its not hard at all that is sure. but it is more useful to have it all in the program itself. and you might get not so tech savvy users with time aswell that will get troubles understanding what it all is. 
put yourself in their shoes.

**Comment by rachmadaniHaryono** [comment]
@AreFinstad i have made a custom line editor for that. it is put beside a button color which reflect the color code from user input.

![selection_011](https://cloud.githubusercontent.com/assets/6340878/21918624/1f8281e6-d98e-11e6-80dd-da041f7b0bf3.png)
