### ISSUE TITLE
simple image editor built in for cropping bad cover images (wrong aspect ratio)

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#91]
ease of use thing for sure, but it would be great if HP could crop out images to be used for covers.
you could then also set a default aspect ratio for the cover images. the cropper could then automatically max that ratio to the height of the image then let the user pick where the cover is.... manual resizing should also be a thing but still atleast have the option to lock the ratio. 

the image does not need to get saved in the archive if those thumbnails gets saved in a more permanent way than a cache (maybe an own folder for saved covers?)

the fastest way and with the fewest program usage to do this now is to get HP to change the cover, while in the explorer window you open the cover in photoshop or whatever. crop it like you normally would do then save it with a new name in the same temp folder for then to go back to explorer and pick the new cover image.
this takes like a min or two if you are really picky. but this could be alot faster if it was a part of the program. also, doing it this way does not save the cover permanently at all i think, once the cache is full it will be gone prob.

**Comment by twiddli** [comment]
Sounds very superfluous. Not something I'd like to use my time making, sorry.
