### ISSUE TITLE
How do I add chapters to tanks etc? O_O

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#92]
when i split it up like this http://i.imgur.com/lTqgdBz.jpg
it becomes like this in happypanda http://i.imgur.com/8luMCK6.jpg

i dont know what im doing wrong :(

also would be neat if i could somehow make it skip everything that isn't .cbz

**Comment by twiddli** [comment]
Check the option `Treat subdirectories as chapters...` in _Application->Gallery_.

Also, please refer to the guide in the wiki on how to import properly.

**Comment by twiddli** [comment]
Forgot to add, ignoring certain file extensions should come in the next version.

**Comment by ghost** [comment]
this is how my file structure is.
Alphabet order > Artist > Chapters/(Tanks > Split chapters)
http://i.imgur.com/vpUC5Xu.jpg
(inside a tank)
http://i.imgur.com/W7j7e00.jpg

do i have to extract every .cbz?

**Comment by CuddleBear92** [comment]
on a note on chapters, i think we need both chapters and volumes added to the edit menu at one point with under titles: https://github.com/Pewpews/happypanda/issues/88
without this in the edit menu you have to rely on the import as stated in the wiki, for me this doesnt work sadly.

**Comment by twiddli** [comment]
Try moving the `Pics` folder out of the tanks and see if that works.

**Comment by ghost** [comment]
i tried it but still no luck, does the same thing as before :s

**Comment by twiddli** [comment]
What methods do you use to import with? 

Have you read the guide on how to import galleries in the wiki? 

Even now, when you import do they still get imported like shown in the second picture in your first post?

**Comment by ghost** [comment]
my file structure is very identical to it and i use "scan for new galleries"

the same thing happens if i drag it as well

**Comment by twiddli** [comment]
Then, the only explanation is that your archives contain folders as well. Is this true?

**Comment by ghost** [comment]
not anymore, i removed folders

right now, there's only .cbz (which means no .cbr as well)

**Comment by twiddli** [comment]
I meant inside your .cbz archives.
Are there only images in them?

**Comment by ghost** [comment]
yeah i always double check before i convert it to .cbz so there's only jpg/jpeg/png in it

**Comment by twiddli** [comment]
I see. Only option left is sending me one of those folders with chapters. I'll test and see if it's a bug. 
Would that be alright with you?

**Comment by ghost** [comment]
i would but my upload speed is 0.4 mb/s and the folder is 20 GB, it'd take like a century for me to upload it :/

all of my chapters are always extracted to see if there's any document/json/folder/pdf in it and then i zip it up

**Comment by twiddli** [comment]
I was talking about one of your galleries, not the whole collection.

**Comment by ghost** [comment]
heres one :P let me know if i need to upload some more http://a.pomf.cat/aokgnp.cbz

**Comment by twiddli** [comment]
Please lookout for #57 which will improve and ease adding chapters to galleries. I'll be closing this issue.
