### ISSUE TITLE
opening edit window and issues in dupe window

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#94]
i think we should be able to open both the edit menu and the hole issue (manga) itself from the dupe window.
atm we can rightclick to show in library and open it that way to check for differences.

hmmm maybe a way to open both at the same time?
like both are mangas are on the same page (let the user move back and forth of the pages are not lined up) and let the user go back and forth on both mangas at the same time to compare it. 

this would prob need an image viewer tho unless you get a built in browser to handle it. (can be done)

**Comment by twiddli** [comment]
It is now possible to edit galleries found be duplicate checking in v0.29.
The image viewer part is too time-consuming and won't be added.
