### ISSUE TITLE
gallery scan loading infinite for me

### ISSUE THREAD

**Issue by ghost** [Pewpews/happypanda#95]
it says at the bottom "loaded 383 of 383" but on the top right corner, i can see it's continuing to scan

is this on purpose or is it a bug because i can hear my hard drive spinning when it does this although it's already been loaded

**Comment by ghost** [comment]
i'm trying with a new install with fresh settings and it does this

https://streamable.com/0rkn

**Comment by twiddli** [comment]
Is the video showing what you're describing in your first post? 

Could you send me your logs?

**Comment by ghost** [comment]
http://pastebin.com/gMzWnHpZ
https://streamable.com/9elu

**Comment by twiddli** [comment]
Hi, please bear with me: 
Firstly, you're very confusing and making it hard to help you. The video you're posting doesn't match what you're describing in the first post. Are these two separate issues or are we talking about the same issues? I know you haven't said anything like this but when I read your descriptions and see your video, they all feel related somehow. 

In any case, if we're talking about multiple issues here then please keep them properly separated in their own issue here on Github. 

I really want to help you. 

Secondly, weirdly enough, your log doesn't contain anything useful. I'd figured that some kind of exception occured and was written to it. Could you retry in debug mode? 

Read how to do it in the _Reporting bugs_ section in the wiki or _Settings->About->Reporting Bugs_.

Thanks.

**Comment by ghost** [comment]
i don't see any happypanda_debug.log when i run it through cmd so i copy pasted what's in my happypanda.log instead

**Comment by twiddli** [comment]
![2016-01-19_15-45-00](https://cloud.githubusercontent.com/assets/11841002/12421722/d6438d3a-bec3-11e5-9811-bd100fd82179.gif)

**Comment by ghost** [comment]
hmm weird, for me it's completely white ..like this

https://streamable.com/9elu

**Comment by twiddli** [comment]
Hi, we can't go further if you're not able to produce a debug log.
Please try and see if the issue still remains in v0.29.
