### ISSUE TITLE
limit search to metadata fields only?

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#98]
i think we should be able to search directly for data fields in our search field. 
for example: author/artist:Mogudan
or: title:[titlename]

you could limit these in " " maybe so it would allow spaces for those that use it.... like: title: [titlename]

these namespace type searches should count for all metadata fields in the program.
also pointing towards: https://github.com/Pewpews/happypanda/issues/88

**Comment by twiddli** [comment]
Please read the Gallery Search guide in the wiki or _Settings->About->Search Guide_, especially under _Special namespaced tags_.

**Comment by CuddleBear92** [comment]
sorry sorry.......
