### ISSUE TITLE
namespace tags should change the metadata fields correctly if it supports it.

### ISSUE THREAD

**Issue by CuddleBear92** [Pewpews/happypanda#99]
namespaces like Language:English and so on should automatically change the Language field into English.
this goes for all namespace fields tho.

this will work very well with tag siblings https://github.com/Pewpews/happypanda/issues/65 as people can start marking artist names as artists and any other tags so they will get namespaces without them having it originally or online.

**Comment by twiddli** [comment]
Akin to #79.
